Rust-SDL2/rust-sdl2

- examples/audio-whitenoise.rs
- src/sdl2/audio.rs
This changes the phantom type `AudioFormatNum` slightly to facilitate impl selection after recent breaking changes in Rust. It does not appear to break the external API.
Also fixes a rename in one of the examples.
Closes #249.
> Upgrade to latest Rust (no breaking changes)

- sdl2-sys/Cargo.toml
- sdl2-sys/build.rs
On OSX using homebrewm at least, building sdl2-sys using pkg-config breaks rustc since the installer places crates in /usr/local/lib, which is where homebrew references dylibs from. This causes rustc to get confused as to which libstd crate it should actually link against, and causes a build error. Since most users were able to make the old build mechanic work, it makes sense (at least for now, I think pkg-config is the way forward in the future) to move building via pkg-config behind a cargo feature.
> move building via pkg-config to behind a feature.

- sdl2-sys/src/controller.rs
- sdl2-sys/src/event.rs
- sdl2-sys/src/haptic.rs
- sdl2-sys/src/joystick.rs
- sdl2-sys/src/keyboard.rs
- sdl2-sys/src/pixels.rs
- sdl2-sys/src/rect.rs
- sdl2-sys/src/rect_2.rs
- sdl2-sys/src/touch.rs
- sdl2-sys/src/version.rs
- sdl2-sys/src/video.rs
- src/sdl2/audio.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/keycode.rs
- src/sdl2/mouse.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/scancode.rs
- src/sdl2/sdl.rs
- src/sdl2/surface.rs
- src/sdl2/version.rs
- src/sdl2/video.rs
Fixes warnings with latest Rust nightly.
https://github.com/rust-lang/rust/commit/7506fe52696c5b3b628f173d74dc4a13b5ccc1f3
> Change deriving to derive

- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/timer.rs
The tricky bit in in `Timer`, which now works a bit differently.
Specifically, we always stop the timer when the `Timer` object is
dropped, because otherwise the closure might run past its lifetime 'a,
rendering the code unsafe.  I'm pretty sure the previous code is buggy.
Note that this pull request is towards the same goal as #263, but does things differently.  I don't use `TraitObject`s -- I don't think it's necessary -- and I already remove the `remove_on_drop` option.  I've been using rust for a week or so so review with care :).
***
Edit: Following the discussion below, I've decided to drop support for Rust closures with SDL timers, and use `extern "C"` functions instead.
> Use unboxed closures throghout the code.

- examples/audio-whitenoise.rs
- sdl2-sys/src/audio.rs
- sdl2-sys/src/controller.rs
- sdl2-sys/src/event.rs
- sdl2-sys/src/haptic.rs
- sdl2-sys/src/joystick.rs
- src/sdl2/audio.rs
- src/sdl2/cpuinfo.rs
- src/sdl2/event.rs
- src/sdl2/keyboard.rs
- src/sdl2/keycode.rs
- src/sdl2/macros.rs
- src/sdl2/mouse.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/scancode.rs
- src/sdl2/sdl.rs
- src/sdl2/surface.rs
- src/sdl2/timer.rs
- src/sdl2/touch.rs
- src/sdl2/version.rs
- src/sdl2/video.rs
Mainly macro syntax changes and using the {:?} format specifier.
Still working on replacing int/uint with isize/usize; will add that to this PR when I'm done.
> Fixes for 1.0 alpha

- examples/audio-whitenoise.rs
- sdl2-sys/src/audio.rs
- sdl2-sys/src/controller.rs
- sdl2-sys/src/event.rs
- sdl2-sys/src/haptic.rs
- sdl2-sys/src/joystick.rs
- src/sdl2/audio.rs
- src/sdl2/cpuinfo.rs
- src/sdl2/event.rs
- src/sdl2/keyboard.rs
- src/sdl2/keycode.rs
- src/sdl2/macros.rs
- src/sdl2/mouse.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/scancode.rs
- src/sdl2/sdl.rs
- src/sdl2/surface.rs
- src/sdl2/timer.rs
- src/sdl2/touch.rs
- src/sdl2/version.rs
- src/sdl2/video.rs
After the recent int / uint debacle and rename to isize and usize, I was wondering why their use is so prevalent in rust-sdl2. As far as I can tell they should not be used as a general purpose integer type in Rust.
This pull request changes the integer types used in events to match the definitions found in SDL_event.h. There is much less casting involved after this change. This will likely break a lot of code, but the recent int -> isize transition also breaks the same code, so I felt this would be a good opportunity for this change.
I also noticed that touch and gesture events use f64 where SDL2 uses f32. This implies greater accuracy than SDL2 provides, so I changed those back to f32, but I'm not sure if this is the right way to go -- those commits can be easily dropped if needed.
I …
> Use correct numeric types for events

- Cargo.toml
This allows a package with sdl2 as its dependency to build with pkgconfig by selecting the feature use-pkgconfig of sdl2.
At this moment you cannot select features of dependencies, so otherwise the feature would be useless unless building sdl2 directly.
> Add pkgconfig feature to sdl2

- src/sdl2/audio.rs
The AudioCVT were removed in PR #269.
This PR revives it with a more familiar interface. 
Now the caller is able to pass in a `Vec<u8>` and have the SDL conversion performed "in place."
(Unless the vector needs additional capacity to handle the conversion.)
---
This is marked with an `#[unstable]` attribute as there are some concerns over a test-case in issue #270.
In short: when going from 1 channel to 4 channels at the same rate: we see behavior which looks like a buffer-overflow.
This same behavior was reproducible when rewriting the test-case in plain C; so there is good reason to believe this is simply a bug in the version of the SDL library being tested.
> Restore the AudioCVT bindings

- examples/demo.rs
In lieu of more sophisticated error handling the function calls should panic rather fail silently.
> Replace `let _ =` with `.unwrap()` in demo.

- src/sdl2/cpuinfo.rs
- src/sdl2/timer.rs
- src/sdl2/touch.rs
- src/sdl2/version.rs
Clean up a few more files using `isize` and `usize` in error.
This came up in #283. These were low-hanging fruit, there is still more to be done before #283 is fixed.
> Correct integer types

- examples/audio-whitenoise.rs
- src/sdl2/audio.rs
Fixes issue #286 
This will break all current uses of AudioSpec. People who don't care
about this value can just set it to 0. Otherwise it must be a power of
2 (per the SDL docs).
> Allow specifying the "samples" field in AudioSpec desired.

- sdl2-sys/src/render.rs
- src/sdl2/audio.rs
- src/sdl2/event.rs
- src/sdl2/mouse.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
These commits should fix the improper usage of isize throughout most of src/sdl. A few improper usages of usize that appeared around the isize instances are fixed as well. keyboard.rs needs to be looked at still, and the casting between i32 and c_int may not really be needed, but may be good for explicitness.
> Audit isize

- src/sdl2/audio.rs
- src/sdl2/macros.rs
- src/sdl2/render.rs
The `impl_raw_accessors!` and `impl_owned_accessors!` macros generate methods that expose raw ffi pointers (`raw()`) and its ownership state (`owned()`) to the public.
These methods are only used for ffi interop, and their use should be discouraged unless absolutely necessary (with an unsafe block).
We certainly don't want to encourage casual use of these functions from user code; raw pointers and ffi interop are inherently unsafe.
`AudioCVT` and `Renderer` also don't require these methods (rust-sdl2 compiles without them), so they were removed.
> Mark raw() and owned() accessors as unsafe, remove unnecessary accessors

- src/sdl2/render.rs
This commit implements get_blend_mode() and set_blend_mode()
for renderer and fixes incorrect get_blend_mode() for texture.
> Blend mode fixes for renderer and texture

- src/sdl2/render.rs
Oops, it appears the two pull requests #288 and #290 changed details about the blend mode that weren't compatible with each other.
This is just a quick fix to that. :)
> Fix conflict with #288 and #290

- src/sdl2/event.rs
- src/sdl2/mouse.rs
SDL lib handles mouse buttons state as a bitmask where each bit
corresponds to a currently pressed button. Constants that map bits
to buttons are defined in C headers, but there are defines only
for the first 5 buttons (left, middle, right, X1, X2). SDL may still
set bits for buttons with num > 5 if they are present and pressed.
Current code runs from_bits(..).unwrap() on them and panics. This patch
replaces the code with from_bits_truncate() that ignores unknown bits.
> Fix panic when mouse is moved while buttons with id > 5 are pressed

- src/sdl2/audio.rs
- src/sdl2/clipboard.rs
- src/sdl2/controller.rs
- src/sdl2/cpuinfo.rs
- src/sdl2/event.rs
- src/sdl2/filesystem.rs
- src/sdl2/gesture.rs
- src/sdl2/haptic.rs
- src/sdl2/joystick.rs
- src/sdl2/keyboard.rs
- src/sdl2/messagebox.rs
- src/sdl2/mouse.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/surface.rs
- src/sdl2/timer.rs
- src/sdl2/touch.rs
- src/sdl2/version.rs
- src/sdl2/video.rs
Just a bit of cleanup.
`ll` was showing up on the Rustdocs, which means users can use it directly. Probably best to encourage people to use `sdl2_sys` for raw bindings instead. :]
> Don't reexport sdl2-sys modules

- examples/renderer-texture.rs
- sdl2-sys/src/pixels.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
Whew, that was a lot of work. Sorry for the large PR. :]
Sooo, most of this is contained within render.rs. All that really changed was: added a Texture lifetime, added `&mut self` to various methods, `RefCell`'d the draw methods, and implemented other ergonomic changes.
This is one of those times where Rust's borrow checker can be overly zealous/too restrictive (`RefCell`), but it generally works in our favor. To my knowledge, no crashes or aliasing problems should be possible.
An example using textures was added: `renderer-texture.rs`
Closes #293
> Make the render submodule safer

- src/sdl2/rwops.rs
This fixes https://github.com/AngryLawyer/rust-sdl2/issues/299 for me. Also `fn write` was deprecated in favor of `fn write_all`.
> std::io -> std::old_io

- src/sdl2/event.rs
- src/sdl2/render.rs
- src/sdl2/version.rs
There's still a tremendous amount of warnings about unstable features, those can be silenced by adding the following crate attribute:
```rust
#![feature(io,core,path,std_misc,collections,libc,hash,rand)]
```
I don't like hiding warnings but for now there's absolutely nothing we can do about those...
> Fix some warnings about deprecated features and unused imports

- examples/game_controller.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
All the basic functions are implemented and I've added an example program.
The SDL2 controller mapping system is a complete trainwreck as far as I'm concerned, you need to parse and generate strings like:
```
030000005e0400008e02000014010000,X360 Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,
```
Maybe we could provide a nice wrapper around that? Although that might be outside of the scope of this lib...
> Added basic support for game controller API

- examples/renderer-texture.rs
- src/sdl2/render.rs
Most of the documentation is pretty much cut-and-paste from https://wiki.libsdl.org/CategoryRender.
Other Rust-specific documentation was added where it was needed.
Other fixes unnoticed from last time:
* copy() and copy_ex() should take a `&Texture`; the texture is never modified by these methods.
* `f64` was changed to `f32`, as SDL uses floats and not doubles
* `SdlResult<>` was removed from some texture methods in favor of panics. These are getters and setters that can only fail if the texture is invalid, which should basically never happen.
> Add documentation to render, other minor fixes

- examples/game_controller.rs
- examples/joystick.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
Unfortunately many functions have very poor error handling: get_axis, get_button and get_hat functions return 0 in case of failure but 0 is also a valid value...
In order to discriminate between the two I call clear_error() before the function and check if an error was reported when the return value is 0. It's pretty hackish but I can't see any other way.
> Add missing methods to GameController API and implement Joystick API

- sdl2-sys/src/audio.rs
- src/sdl2/audio.rs
- src/sdl2/lib.rs
The `AudioCallback` trait must implement [`Send`](http://doc.rust-lang.org/std/marker/trait.Send.html).
`Send` declares that the audio callback data is safe to be sent across other threads (i.e. the audio callback thread).
As a result, types that can only be used on a single thread, such as `Rc<T>`, raw pointers and even our own `Renderer`, cannot be sent.
As long as the struct implementing `AudioCallback` does not include any non-Sendable fields, user code should compile without explicitly having to declare `Send`. Notice the audio-whitenoise example didn't change at all.
The only drawback is that `Send` imposes a `'static` lifetime. That means no (non-static) references are allowed to be stored in the audio callback. However, the restriction should (hopefully) be lifted soon with …
> Audio thread safety, improve AudioCVT

- examples/audio-whitenoise.rs
- examples/game_controller.rs
- sdl2-sys/build.rs
- sdl2-sys/src/lib.rs
- sdl2-sys/src/rect.rs
- src/sdl2/audio.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/gesture.rs
- src/sdl2/haptic.rs
- src/sdl2/keycode.rs
- src/sdl2/lib.rs
- src/sdl2/pixels.rs
- src/sdl2/scancode.rs
- tests/lib.rs
- Update `derive(Show)` to the new recommended `derive(Debug)`.
- Use `#![feature()]` tags for path, io, libc, and others, as necessary.
A clean rebuild no longer has any warnings.
> Fix All Compile Warnings

- src/sdl2/render.rs
I queued up some Renderer changes over the course of two days so that it's all in one nice PR. :)
So, `Renderer::drawer()` now returns a simple `RenderDrawer<'renderer>` instead of `RefMut<RendererDrawer>`. This is actually to address a safety concern.
You were literally able to swap the RenderDrawers of two renderers. This is what you get when you have mutable references to things. :|
```rust
fn swap_drawers(r1: &Renderer, r2: &Renderer) {
let d1_mut = r1.drawer().deref_mut();
let d2_mut = r2.drawer().deref_mut();
// whaaaattt...
std::mem::swap(d1_mut, d2_mut);
}
```
You can't do this anymore because `Renderer::drawer()` returns a value and not a mutable reference or a type with `DerefMut`.
As I was writing this PR, I caught the same issue with `RenderDrawer::render_target()`. It now …
> Renderer changes

- Cargo.toml
- sdl2-sys/Cargo.toml
- sdl2-sys/src/lib.rs
- src/sdl2/lib.rs
Using a different version can cause annoying conflicts when used with packages that do use the crates.io version, like `gl-rs`:
expected `extern "C" fn(u32, *const libc::types::common::c95::c_void) -> u32`,
found `extern "C" fn(u32, *const libc::types::common::c95::c_void) -> u32`
(expected enum `libc::types::common::c95::c_void`,
found a different enum `libc::types::common::c95::c_void`) [E0308]
I'm not sure if a catchall version is appropriate, though.
> Use crates.io libc.

- src/sdl2/timer.rs
While I certainly improved the failure rate of the tests, it still wasn't perfect.
There seems to be some underlying safety issue with lazily initializing the timer subsystem from multiple threads. (See my comments on issue #314.)
This simple fix forces the timer tests to run sequentially using a static mutex. While the test holds this lock it is safe to call `sdl::init(INIT_TIMER)` without interfering with any other tests.
---
Previously I got about 5 failures per 100 iterations of the test suite. With these improvements I see no failures in _1000 iterations._
NOTE: PR #325 seems to have failed Travis as a result of such a spurious failure.
> Fix spurious timer test failures

- src/sdl2/render.rs
> Fix the array slice's size, as yielded by `Texture::with_lock()`.

- Cargo.toml
- sdl2-sys/build.rs
- src/sdl2/lib.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- Added crates.io rand crate as dependency.
- Replaced std::os:getenv by std::env::var.
- Replaced std::slice::from_raw_mut_buf by
std::slice::from_raw_parts_mut.
- Replaced std::cell::try_borrow_mut by std::cell::borrow_state.
> Fixed a few deprecation warnings.

- examples/renderer-yuv.rs
- sdl2-sys/src/render.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
Woo, some more render changes!
Again, the changes are all rolled into one nice PR.
* You can now obtain old textures that were set in `RenderTarget`, as brought up in #335.
* It's important to get render target textures back for drawing. Doing so is the entire point of `RenderTarget`.
* Hopefully, the YUV slice length issue from #334 is solved once and for all.
* Multiple-of-two dimensions and pitches are required for planar YUV formats.
* `Renderer::create_texture()`, `Texture::update()` and `Texture::update_yuv()` will return an error if they're not supplied.
* Unfortunately, SDL doesn't perform this check for us. It's crucial
that we guarantee this for `rust-sdl2` because array slice lengths
must be predictable and derivable.
* A YUV example was added to solidify our understanding of …
> More renderer changes

- .travis.yml
- sdl2-sys/Cargo.toml
- sdl2-sys/build.rs
This commit ensures the pkg-config crate will only be downloaded when
the feature is enabled.
An additional test has been added to travis to ensure it will also be tested properly
> Only use the pkg-config dep when needed

- src/sdl2/lib.rs
Slicing syntax is stable in the 1.0 nightly, we no longer need to explicitly mark it as feature.
> Feature for slicing syntax no longer required

- Cargo.toml
- src/sdl2/surface.rs
This matches the SDL header behavior. `blit_scaled` is a copy of `upper_blit_scaled` (users shouldn't incur any penalty if currently using `upper_blit_scaled`.)
resolves #328
> expose SDL_UpperBlitScaled as blit_scaled

- examples/audio-whitenoise.rs
- src/sdl2/audio.rs
- src/sdl2/keycode.rs
- src/sdl2/render.rs
- src/sdl2/scancode.rs
The main changes are:
* Hash changes and the removal of hash::Writer
* Requirement to acknowledge phantom types and lifetimes
* Fixed with the new `PhantomFn` trait
Consequentially, `AudioCallback` now uses an associated type for the channel scalar. This was the most intuitive way to resolve the phantom type problem in `AudioFormatNum` without adding `PhantomData` markers everywhere (or inside `AudioSpecDesired`).
Adding the associated type to `AudioCallback` also means that you can no longer implement an `AudioCallback` of multiple channel scalars simultaneously (say, both `f32` and `u8`).
I believe this is better, as it eliminates conflicting trait implementations and any confusion caused by them.
This change is similar to how [`Iterator`](http://doc.rust-lang.org/std/iter/trait.Iterator …
> Fixes for Rust nightly

- examples/audio-whitenoise.rs
- examples/demo.rs
- examples/game_controller.rs
- examples/joystick.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- sdl2-sys/src/event.rs
- src/sdl2/event.rs
- src/sdl2/sdl.rs
- tests/lib.rs
**If this is merged, it will cause quite a disturbance: literally every SDL2 project will break!**
This is the result from what was discussed in #324.
```rust
/// sdl2::init(...);
/// sdl2::quit();
let sdl_context: sdl2::Sdl = sdl2::init(...).unwrap();
// `SDL_Quit()` is called automagically!
```
The most obvious change here is that you no longer have to call `sdl2::quit()`. Once the `Sdl` type is dropped, cleanup is done automatically.
The _true_ reason the SDL "context" object was added was for thread safety reasons.
Some of SDL's types and functions require initialization or use exclusively on the main thread (such as `SDL_PumpEvents()`, `SDL_Window`). Adding a non-`Send`able type that represents the SDL main thread gives Rust a way to statically guarantee that event pumping (and later …
> EventPump and sdl2::Sdl context type

- examples/audio-whitenoise.rs
- sdl2-sys/src/lib.rs
- src/sdl2/event.rs
- src/sdl2/keyboard.rs
- src/sdl2/lib.rs
This commit fixes errors and clean all warnings about deprecated and unused stuff.
> Update to rustc 1.0.0-dev (c9b03c24e 2015-03-12) (built 2015-03-13).

- src/sdl2/audio.rs
- src/sdl2/keyboard.rs
- src/sdl2/lib.rs
- src/sdl2/rwops.rs
- src/sdl2/surface.rs
- tests/lib.rs
This is an update to the new IO. It also uses the new Path module. This makes it a breaking change for anyone using RWOps.
Furthermore, I changed an unnecessary use of Vec::from_raw_buf, as slice::from_raw_parts was enough.
The only function that need a look at is the flush() method for io::Write. Currently it just returns Ok, without actually doing anything.
> Update io, path and collections

- sdl2-sys/src/audio.rs
- sdl2-sys/src/render.rs
- src/sdl2/audio.rs
- src/sdl2/event.rs
- src/sdl2/render.rs
* `range(a,b)` was removed, so I updated it to `(a..b)`
* as_slice is unstable and in our case not needed
* Some transmutes could easily be replaced by other functions. I changed these so the code would hopefully be a little clearer.
* During the change above, I updated some `*const` to `*mut` in sys as that reflected the upstream better.
> Fix range, remove as_slice and some transmutes

- sdl2-sys/src/audio.rs
- sdl2-sys/src/event.rs
- sdl2-sys/src/touch.rs
- src/sdl2/audio.rs
- src/sdl2/controller.rs
- src/sdl2/joystick.rs
- src/sdl2/keycode.rs
- src/sdl2/lib.rs
- src/sdl2/render.rs
- src/sdl2/scancode.rs
- src/sdl2/sdl.rs
- src/sdl2/timer.rs
- src/sdl2/video.rs
* Implement Clone where Copy is needed
* Remove all uses of `unsafe_destructor`, these are no longer needed
* Remove the `BorrowState`, this way we only need `std_misc` when testing
> Fix Copy, plus reduce the used features

- .travis.yml
- sdl2-sys/Cargo.toml
- sdl2-sys/src/audio.rs
- sdl2-sys/src/controller.rs
- sdl2-sys/src/event.rs
- sdl2-sys/src/haptic.rs
- sdl2-sys/src/lib.rs
- sdl2-sys/src/rect.rs
- sdl2-sys/src/timer.rs
- sdl2-sys/src/video.rs
This way sdl2-sys will compile on the beta channel.
If needed, sdl2-sys can be compiled using `cargo build --features no_std`.
> Move no_std from sdl2-sys to a cargo feature

- examples/audio-squarewave.rs
- examples/audio-whitenoise.rs
- src/sdl2/audio.rs
It's me, again!
Here are some functional improvements to the audio API. Basically, the way the audio device is opened is now changed to account for fallback values and obtained AudioSpecs.
```rust
let desired_spec = AudioSpecDesired {
freq: 44100,
channels: 1,
samples: 0,
callback: MyCallback { actual_freq: ??? }
};
let device = desired_spec.open_audio_device(None, false).unwrap();
```
becomes
```rust
let desired_spec = AudioSpecDesired {
freq: Some(44100),
channels: Some(1),
samples: None          // get default sample size
};
let device = AudioDevice::open_playback(None, desired_spec, |spec| {
MyCallback { actual_freq: spec.freq }
}).unwrap();
```
`AudioDevice::open_playback` seems more natural to me than "opening an AudioSpec".
---
There's now no way to open a capturing audio device; …
> Audio API changes

- src/sdl2/video.rs
I needed that to create a debug OpenGL context.
On a side note, the current `gl_set_attribute` interface is a bit ugly rust-wise because it's obviously completely type-unsafe. You have to cast all the parameters down to `i32`, if you mixup the parameters and use a `GLProfile` instead of a `GLContexFlag` your code will mess up without any warning.
> Add missing flag values for GLContextFlags attribute

- src/sdl2/render.rs
- src/sdl2/video.rs
This is a quick and dirty fix that allows accesses to Window getters using a shared `&Window` reference.
Fixes #394
> Allow accesses to Window property getters with `&Window`.

- Cargo.toml
- sdl2-sys/Cargo.toml
- src/sdl2/audio.rs
- src/sdl2/surface.rs
- src/sdl2/timer.rs
Updated num dependency to 0.1.23
Updated version to 0.2.2
> Removed stability and deprecation attributes that can no longer be used outside of std

- src/sdl2/keycode.rs
- src/sdl2/rwops.rs
- src/sdl2/scancode.rs
The derivation was not used anymore, and it seems that AsOsStr is not needed anymore either.
Fixes building on latest nightly.
> Remove #[derive(FromPrimitive)] and use AsOsStr

- README.md
- sdl2-sys/src/video.rs
- src/sdl2/video.rs
Careful with this pull request, I'm a rust newbie! :)
I think there is a problem with the return type of SDL_GL_GetProcAddress. This C function returns a `const void*` pointer and not a rust `Option<extern "system" fn()>` data type. So there should be at least a change in the `sdl2-sys`-part.
The next issue is whether to use `Option<extern "system" fn()>` or `*const c_void` as return type in the rust API. For the moment I changed it to `*const c_void` as both gl-rs and glium seem to prefer this return type. It is not the "rust way" of doing it, but for the usual use case it creates the least friction. 
Maybe - and this is a question for the designers/maintainers - the best way would be to provide a rust `gl_get_proc_address` function with `Option<extern "system" fn()>` return type and a …
> first approach to fix SDL_GL_GetProcAddress

- src/sdl2/audio.rs
- src/sdl2/event.rs
- src/sdl2/mouse.rs
- tests/lib.rs
* `audio` no longer exposes aliased ffi constants; an enum is used for `AudioFormat` instead.
* `MouseState` is now a `struct` and not a `bitflag!`. It's now easier to test for buttons (`state.left()` instead of `state.contains(sdl2::mouse::LEFTMOUSESTATE)`).
> Some bitflag! and const tidyup from mouse and audio

- sdl2-sys/src/pixels.rs
- src/sdl2/pixels.rs
- src/sdl2/surface.rs
* `SurfaceFlag` was deprecated in SDL2 and actually does nothing.
`SDL_CreateRGBSurface()` simply ignores the flag.
* `SDL_CreateRGBSurface()` internally converts the parameters from pixel masks to a
`PixelFormatEnum` anyway, which means that we can simplify `Surface::new()` to work
for most use cases.
For passing masks explicitly, there's `Surface::from_pixelmasks()`.
* width, height and pitch are unsigned.
> Remove SurfaceFlag, Surface::new uses PixelFormatEnum

- sdl2-sys/src/joystick.rs
- src/sdl2/audio.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
- src/sdl2/keycode.rs
- src/sdl2/mouse.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/scancode.rs
- src/sdl2/sdl.rs
- src/sdl2/version.rs
- src/sdl2/video.rs
In particular, try to derive as much as possible from:
`#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug]`
> Add #[derives] (Copy, Clone, Hash, etc.) where they can be added

- examples/demo.rs
- examples/game_controller.rs
- examples/joystick.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- examples/window-properties.rs
- src/sdl2/event.rs
- src/sdl2/render.rs
- src/sdl2/sdl.rs
- src/sdl2/video.rs
The changes are only slightly breaking. Most people will only need to change the SDL context at the beginning of their program to be mutable:
```rust
let mut sdl_context = sdl2::init().video().build().unwrap();
```
To acquire an `EventPump`, it now requires a mutual borrow of `Sdl`. This is to statically ensure a single event loop, and that it's never possible to have two or more event loops at a time.
It's no longer necessary to create a dummy `EventPump` handle in functions that only access window properties. `properties()` accepts `&Sdl` instead of `&EventPump`:
```rust
fn set_title(&mut self, value: &str) {
self.window.properties(&self.sdl_context).set_title(value).unwrap();
}
```
is equivalent to the old
```rust
fn set_title(&mut self, value: &str) {
let event_pump = …
```
> Make EventPump exclusively borrow the SDL context

- src/sdl2/audio.rs
- src/sdl2/rwops.rs
- src/sdl2/surface.rs
- tests/lib.rs
* `SDL_RWFromConstMem` and `SDL_RWFromMem` only references the
buffer, and never copies it - ergo, lifetime.
* `AsRef<Path>` lets us use ordinary string slices as path arguments,
like in `std::fs::File`.
> Add lifetime to RWops, coerce Paths, update audio/surface RWops functions

- examples/demo.rs
- examples/game_controller.rs
- examples/joystick.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- examples/window-properties.rs
- src/sdl2/audio.rs
- src/sdl2/clipboard.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/filesystem.rs
- src/sdl2/joystick.rs
- src/sdl2/keyboard.rs
- src/sdl2/lib.rs
- src/sdl2/messagebox.rs
- src/sdl2/render.rs
- src/sdl2/sdl.rs
- src/sdl2/util.rs
- src/sdl2/video.rs
#413 should be merged first - this updates its example.
Diff excluding the EventPump stuff: https://github.com/AngryLawyer/rust-sdl2/commit/f4d6e65ea38e6182824fb6da6f8550f8b6d468cb
* The expression `CString::new(s).unwrap().as_ptr()` creates a
dangling pointer; the underlying `CString` value gets dropped
shortly after the pointer is obtained. The correct method is to let
the `CString` live longer than the pointer by assigning it to a
variable, then calling `.as_ptr()` on the variable later.
* Instead of always `unwrap()`ing `CString`s (and risking panics),
handle NulError in one of two ways:
* Return an `SdlResult` or "no match" value when used with "getter"
functions.
* Remove nuls when used as displayed strings (e.g. Window titles).
> Fix dangling pointers from CString, deal with interior nul bytes

- src/sdl2/video.rs
For glium and [`glium_sdl2`](https://github.com/nukep/glium-sdl2) — shameless plug :) —, it's required to check if an OpenGL context is the current one in the thread. Using `context == gl_get_current_context()` doesn't work because the `owned` fields would always be different.
I removed `gl_get_current_context()` to guarantee unique OpenGL context objects that always get deleted, but its functionality lives on in `GLContext::is_current()` and `Window::gl_set_context_to_current()`.
> GL context

- src/sdl2/event.rs
Certain event types are disabled by default in SDL2, such as `DropFile`, `TextInput` and `TextEditing`.
To use them, it's necessary to enable them manually:
```rust
sdl_context.event_pump().enable_event(EventType::DropFile);
```
> Query, enable and disable event types

- examples/demo.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- examples/window-properties.rs
- src/sdl2/macros.rs
- src/sdl2/render.rs
Closes #411 
The methods from `RenderDrawer` have been moved into `Renderer`.
As well as with the upcoming "controller" pull request, I'm attempting to convert `i32` (`int`) values into `u32` values wherever negative values don't make sense (such as width, height, counts and indices). This is explained further in src/sdl2/macros.rs.
> Move drawer methods into Renderer

- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
- src/sdl2/macros.rs
Throughout the library, I'd like to replace all "non-value" enum variants (the "Nones", "Invalids", etc.) with `Option::None`.
Constants such as `SDL_CONTROLLER_AXIS_INVALID` exist to communicate errors to the caller, yet they aren't polymorphic to the other variants; `Axis::Invalid` must be ignored or treated differently from the other axes because it doesn't indicate a "real" axis. This is basically a rewording of the "null" problem.
`-> SdlResult<T>` is changed to `-> T` for functions that cannot fail.
As well as with the "renderer" pull request, I'm attempting to convert i32 (int) values into u32 values wherever negative values don't make sense (such as width, height, counts and indices). This is explained further in src/sdl2/macros.rs.
> Controller stuff

- Cargo.toml
- README.md
Helpful to have a link to the documentation from the Crates page, and GitHub README.
> Adding documentation links

- sdl2-sys/src/surface.rs
- src/sdl2/keyboard/mod.rs
- src/sdl2/macros.rs
- src/sdl2/mouse.rs
- src/sdl2/rect.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
"owned" has been removed from the remaining types: `Surface`, `Window`, and `Cursor`.
The "owned" flag in these types directly encourages type aliasing and ad-hoc borrowing, which is problematic. Whenever these types can be borrowed, it can be done with saner and much clearer semantics (i.e. with references + lifetimes!).
There's a method, `WindowProperties::get_surface()`, that borrows the window's surface. Because we maintain that `Surface` is solely used for _owned_ surfaces (ones that we free), a new "borrowed surface" type needed to be created: `SurfaceRef`. `SurfaceRef` is a DST whose reference transmutes cleanly to `*mut SDL_Surface`.
```rust
// OLD: fn WindowProperties::get_surface(&mut self) -> SdlResult<Surface>
fn WindowProperties::get_surface(&self) -> SdlResult<&SurfaceRef> …
```
> Remove the "owned" flag from all types

- src/sdl2/joystick.rs
Fixes an error `malloc: *** error for object 0xa000000000000000:
pointer being freed was not allocated` when closing window.
> Check whether joystick is attached before freeing

- sdl2-sys/src/surface.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
In PR #435, I made `SDL_Surface` a DST. This is actually invalid because the resulting pointer `*mut SDL_Surface` became a fat pointer (i.e. 16 bytes instead of 8 on 64-bit targets).
Unsized types (as opposed to dynamically sized types) in Rust aren't currently possible.
To prevent partial swapping and memory corruption with `std::mem::swap()`, the structure is 0 bytes.
This shouldn't cause any problems, as `SurfaceRef` is always a reference to SDL-owned memory.
> Make `SurfaceRef` 0 bytes

- README.md
- examples/audio-squarewave.rs
- examples/audio-whitenoise.rs
- examples/demo.rs
- examples/game_controller.rs
- examples/joystick.rs
- examples/keyboard-state.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- examples/window-properties.rs
- src/sdl2/audio.rs
- src/sdl2/clipboard.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
- src/sdl2/keyboard/mod.rs
- src/sdl2/mouse.rs
- src/sdl2/render.rs
- src/sdl2/sdl.rs
- src/sdl2/timer.rs
- src/sdl2/video.rs
Feel free to sit on this. I'd like a chance for some feedback before this all gets merged. [**Documentation**](https://nukep.github.io/rust-sdl2/sdl2/).
Closes #431
**There are new subsystem types for each subsystem**: `VideoSubsystem`, `AudioSubsystem`, `JoystickSubsystem`, etc.
```rust
let sdl_context = sdl2::init().unwrap();
let video_subsystem = sdl_context.video().unwrap();
let window: Window = video_subsystem.window("Test", 800, 600).build().unwrap();
```
Types that cannot outlive SDL, such as `Window`, `Joystick`, `GameController`, and `AudioDevice`, all contain an `Rc` to their respective subsystems. They each include something like `Rc<VideoSubsystem>`. In turn, each subsystem includes `Rc<SdlDrop>`.
**This means that SDL and the subsystems will only be quit once nothing depends …
> Subsystems and lifetimes

- README.md
- examples/audio-squarewave.rs
- examples/audio-whitenoise.rs
- examples/demo.rs
- examples/game_controller.rs
- examples/joystick.rs
- examples/keyboard-state.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- examples/window-properties.rs
- src/sdl2/audio.rs
- src/sdl2/clipboard.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
- src/sdl2/keyboard/mod.rs
- src/sdl2/mouse.rs
- src/sdl2/render.rs
- src/sdl2/sdl.rs
- src/sdl2/timer.rs
- src/sdl2/video.rs
This is built on top of PR #441. Here's the relevant commit for this PR: https://github.com/AngryLawyer/rust-sdl2/commit/5d8e866739bfc33e10cbe7d2b896669a4d5e6d46
So, `WindowProperties` is overkill for most use cases. I realized that it can be eliminated and still meet the safety criteria for `get_surface()` (i.e. the event loop can't run and the window can't mutate because it would reallocate the surface).
```rust
// Old
window.properties(&event_pump).set_title("Hello!");
let s = window.properties(&event_pump).get_surface();
// New
window.set_title("Hello!");
let s = window.get_surface(&event_pump);
```
`Renderer` needed a method to access the underlying window, so I implemented `WindowRef` in a similar fashion to `SurfaceRef` in #435. It's not an option to expose `&mut Window` because …
> Remove WindowProperties, implement WindowRef

- sdl2-sys/src/render.rs
- sdl2-sys/src/surface.rs
- sdl2-sys/src/video.rs
This closes https://github.com/AngryLawyer/rust-sdl2/issues/442. I claim that `c_void` makes sense because these types are only ever used as pointers.
> Replace empty #[repr(C)] structs with c_void wrappers.

- src/sdl2/event.rs
SDL_PeepEvents returns the number of events it put in the buffer, which is
usually less than max_amount.
> Don't return garbage events from peek_events

- examples/demo.rs
- examples/keyboard-state.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- examples/window-properties.rs
- Changed 'while' loops into 'loop'-type loops with a lifetime, thus eliminating 'running' variable
- Moved 'use' statements out of the loop (one time is enough)
I think that looks a bit nicer.
> Changes in example loops

- src/sdl2/mouse.rs
This allows the method to be used with the result of `Renderer::window()`.
> Change parameter for `warp_mouse_in_window` from `Window` to `WindowRef`

- src/sdl2/audio.rs
- src/sdl2/clipboard.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/filesystem.rs
- src/sdl2/hint.rs
- src/sdl2/joystick.rs
- src/sdl2/keyboard/keycode.rs
- src/sdl2/keyboard/scancode.rs
- src/sdl2/render.rs
- src/sdl2/sdl.rs
- src/sdl2/version.rs
- src/sdl2/video.rs
Compiles using 1.5 and 1.6; both handle the rs-sdl2-examples just fine. That's all I know :)
> Fix compilation on arm using Rust 1.5

- sdl2-sys/Cargo.toml
- sdl2-sys/src/lib.rs
- sdl2-sys/src/video.rs
I replaced num::FromPrimitive in /sdl2-sys/src/video.rs with own trait FromPrimitive, then removed num dependency from sdl2-sys.  I also made a minor alteration to the implementation of the trait so as to make the code compile.
> Removed num dependency from sdl2-sys

- Cargo.toml
- sdl2-sys/Cargo.toml
- sdl2-sys/src/audio.rs
Also bumped patch version on sdl2-sys and sdl2. Now there are no more warnings when compiling on rust stable (1.6)
> Removed #[allow(raw_pointer_derive)] from sdl2-sys

- src/sdl2/surface.rs
At the moment, the blit() family of functions takes an argument of type `S: AsMut<SurfaceRef>`. This is obviously supposed to allow code like the following:
```rust
let mut dest: Surface = ...;
sprite.blit(None, &mut dest, Some(sprite_rect));
```
However, this trait isn't implemented for SurfaceRef itself. So while an owned Surface will work, there's no way to pass a SurfaceRef as the destination.
I've changed the type signature to take a `&mut SurfaceRef`, to which a `&mut Surface` will automatically coerce (thanks to DerefMut). In other words, code like the above should still compile, though I doubt there's much out there compared to how many applications are using Renderer.
> SurfaceRef blit functions: Pass destination argument as &mut SurfaceRef

- src/sdl2/surface.rs
Since `Rect` is `Copy`, the closure passed to `Option<Rect>::map()` is working with a copy of the data, not the original. This pointer is invalid once the closure ends. Fix that by working on a reference instead of a value.
Fixes #498
> Surface blit crash: Get rect ptr from ref instead of dead temp

- src/sdl2/messagebox.rs
currently the function uses an Option<&Window> to specify a parent window. this no longer works with the WindowRef you get out of Renderer.window(); this pull request makes it take an Option<&WindowRef> instead.
> change show_simple_message_box to use WindowRef

- Cargo.toml
- src/sdl2/keyboard/mod.rs
- src/sdl2/messagebox.rs
- Bumped to 0.18.0
Replaced “ll” with “::sys::messagebox”, because “ll” does not work.
> Updated to latest bitflags

- Cargo.toml
- README.md
- sdl2-sys/Cargo.toml
- sdl2-sys/build.rs
- sdl2-sys/src/sdl.rs
It's currently difficult to use rust-sdl2 and have it link against the Mac framework version of SDL2 (rather than the version installed by MacPorts or Homebrew), especially if you want to build with cargo.  This change adds a `use_mac_framework` feature flag that dependents can easily set or re-export in their `Cargo.toml`, and adds instructions for using it to the README.
> Add feature flag and instructions to use Mac SDL2 framework

- src/sdl2/controller.rs
Useful for hot swapping when using the GameController API.
> Added instance_id to GameController to get it's JoystickId

- README.md
Hey, I think we can remove the link in the README to my examples project. While I do get the occasional PR to update things when this repo has breaking changes, I don't have the time to maintain it.
For my games I also end up just writing some c platform code to a expose a simpler api, so I don't really follow this project anymore.
> Remove link to rs-sdl2-examples project

- src/sdl2/render.rs
Necessary to use TextureValueError with brson's error-chain crate.
> Implement Error for TextureValueError

- README.md
Found a change in file structure for Rust 1.6 on Windows, and I also tested the files in a folder that wouldn't be changed when updating Rust, with the system environment LIBRARY_PATH variable set.
> add lib locations for windows setup

- README.md
> Update README to note that latest stable Rust is targeted

- src/sdl2/render.rs
- src/sdl2/rwops.rs
The ownership is a little squirrelly but this seems the best way, as far as I can tell.  The other option seems to be to make the RWops object actually hold on to a buffer.  Or just force everyone to implement this from scratch, but the lifetime implications actually get sort of tricky so it'd be nice to have a version for anyone to use.
Addresses issue #535.
> Added a from_read() method to RWops

- examples/message-box.rs
- sdl2-sys/src/messagebox.rs
- src/sdl2/messagebox.rs
- Added show_message_box in the submod messagebox
- Added several structs and enum next to it
- Added a messagebox example in examples/ to :
- allow users to test it quickly
- have something for the devs to test this feature quickly
Also changed some minor stuff in show_simple_message_box,
but it shouldn't break the current API
> Added show_message_box

- src/sdl2/audio.rs
According to [the SDL documentation](https://wiki.libsdl.org/SDL_QueueAudio) the third parameter to the `SDL_QueueAudio` takes the number of bytes, not samples.
> Pass the number of bytes instead of the number of samples in AudioQueue::queue

- README.md
I've been using these SDL2 bindings via glium-sdl on Windows. This PR adds instructions to the README.md that work for me. I based the instructions on the minGW instructions. I use rustup so I don't know if the paths are exactly correct for the other installation options but like I said, I based them off the existing windows instructions. I use a `LIB` env variable so I know that part of the instructions is correct.
For me the location involving `AppData` was wrong so I updated that too. I don't know if that means rustup changed the path at some point or what.
Furthermore, I'm not seeing the segfault during init that some folks have seen on Windows. Perhaps because it's all built with msvc or maybe one of the dependencies just handles that case.
> Add MSVC install instructions

- Cargo.toml
Rust-SDL2 does not use anything from num aside from FromPrimitive/ToPrimitive. Using num-0.1.25 we can opt out of unneeded features like bigints or complex numbers.
This also improves compile times of clean builds.
> use num-0.1.25 to opt out of unneeded features

- sdl2-sys/src/event.rs
- src/sdl2/event.rs
- src/sdl2/mouse.rs
https://github.com/AngryLawyer/rust-sdl2/issues/555 As described here we are missing the direction field from the MouseWheel event in SDL2.  This commit adds that field in.
> Add direction field to MouseWheel event

- src/sdl2/render.rs
Native SDL2 behavior allows passing of null to fill the entire target.
Unless there's some reasoning not to allow this?
> Renderer.fill_rect now takes an Option<Rect>.

- src/sdl2/event.rs
Fixes a crash when pressing any key on linux. 
Not completely sure why linux has something extra here (doesn't seem visible in sdl2's source) but I wasn't the only one with this issue.
> Ignore unrecognized keyboard modifiers

- sdl2-sys/src/keyboard.rs
- src/sdl2/event.rs
This also reverts the change in 9604e85f3db1881654c2d23924fc0b08f7948b94 which just hid the issue.
Sorry about that, should have dug deeper before PR'ing.
The break was most likely caused by https://github.com/rust-lang/rust/pull/37429 recently landing
> Add missing `#[repr(C)]` to SDL_Keysym

- .travis.yml
Should fix the Travis build.
Appears SourceForge changed some of there download mirror domain names.
> Fix SDL2_gfx download link

- src/sdl2/image/mod.rs
- src/sdl2/mixer/mod.rs
- src/sdl2/ttf/mod.rs
Hi!
I don't think you can set arbitrary cfg attributes from the command line in cargo (please correct me if I'm wrong), so the only way to conditionally compile some code with command line options to cargo is by using a feature. I noticed the "use_mac_framework" feature already existed, and it was being checked in some places but not others.
> Check feature use_mac_framework with mac_framework

- src/sdl2/pixels.rs
I did not include conversions to sdl2_sys structs containing pointers, since that could be unsafe.
I also did not include a From<ll::SDL_PixelFormatEnum> for PixelFormatEnum because upstream changes could break code and make conversion not succeed every time.
> Add primitive conversions for structs in pixels module

- src/sdl2/rect.rs
Implements Deref, DerefMut, AsRef, AsMut, Into, and From for Point around ll::SDL_Point.
> add trait bounds for primitive conversions on Point

- src/sdl2/image/mod.rs
- src/sdl2/mixer/mod.rs
It occured to me that instead of `&Path` a more generic approach could be used. So I've replaced some usages of &Path in code with `P: AsRef<Path>`.
> Use AsRef<Path> instead of &Path

- src/sdl2/video.rs
SDL will happily return 0 (on Linux) if you ask what profile it will use without explicltly setting one... even after you have already gotten a GL context.  So even if you do something seemingly innocuous such as:
```
let window = video.window(window_title, screen_width, screen_height).opengl().build();
let gl = video.gl_attr();
println!("Got GL {}.{}, profile {:?}",
gl.context_major_version(),
gl.context_minor_version(),
gl.context_profile());
```
the `gl.context_profile()` call can return something unrecognized and panic.
> Added Unknown value to GLProfile

- src/sdl2/render.rs
Hello again!
I've decided it would be convenient to use `Into<_>` trait for parameters in `draw_point`, `draw_points`, `draw_line` and `draw_lines`, so one can just write `draw_line((0, 0), (x, y))` instead of creating Point instances for that case.
> use Into<_> bounds for draw_point(s) and draw_line(s) fns

- src/sdl2/render.rs
The Rect structure was being freed before the raw pointer was passed to
SDL_RenderFillRect(), leading to garbage rect values, which caused SDL
to not actually draw any rectangle (or sometimes, it drew a rectangle
over the entire window).
> Fix use-after-free in Renderer::fill_rect()

- src/sdl2/image/mod.rs
Both the implementation and use of the impl of `ToString` for `image::InitFlag` involve a lot of `.to_string()` calls and string concatenation when they do not need to. This PR proposes to replace them with a more appropriate use of the formatting machinery.
Note that `ToString` is automatically implemented for types that implement `Display`, so no functionality has been removed.
> Reduce allocation churn in image init error handling

- README.md
Shorten/optimize the build script instructions and make them only copy DLLs, not including the license files unpacked from those directories.
> Update build script instructions

- sdl2-sys/src/sdl.rs
The buildscript is sufficient for specifying the link flags in all cases. In newer versions of Rust, the redundant linker flags generate a warning.
Tested on Linux and Windows, with and without `use-pkgconfig` feature. I don't have an OSX system to test on.
> Remove redundant #[link] attributes (fixes #615)

- examples/audio-queue-squarewave.rs
- src/sdl2/audio.rs
- src/sdl2/event.rs
- src/sdl2/gfx/primitives.rs
- src/sdl2/messagebox.rs
- src/sdl2/rect.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/ttf/font.rs
- src/sdl2/video.rs
This PR addresses https://github.com/AngryLawyer/rust-sdl2/issues/562
**This will require a major version bump as there are breaking changes in here.**
The Atom whitespace package strikes again!  Files I modified had extraneous whitespace characters automatically removed.  If this is a problem I can update the commit to not include those.  Formatting was not modified by this PR except where necessary.
> Update APIs to use Into<Option> instead of Option

- src/sdl2/rect.rs
> Clarify Rect docs to indicate that empty Rects aren't allowed

- src/sdl2/hint.rs
Let's decide on documentation, namespacing, etc for a single function before diving into a ton of more complex hints.
> Implement sdl2::hint::video_minimize_on_focus_lost

- src/sdl2/rect.rs
> Fix bug in Rect::contains, clarify docs, and add doctests for it.

- changelog.md
- src/sdl2/gfx/primitives.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/ttf/font.rs
This reduces the size of the type and eliminates the need to branch to read from it, increasing its usability, and bringing it closer to the conceptual Color type used by most libraries and SDL itself.
This *is* a breaking change, but the `RGB` and `RGBA` constructor functions should make the impact minimal for anybody not manually matching.
I suppose I should make a note about some of the other inconsistencies; `raw()` is private, "because reasons", but `Color` implements `Into<ll::SDL_Color>` meaning the conversion is publicly available as safe anyways, and the `ttf` module seems to independently re-implement this function for no discernible reason. This could perhaps also be improved.
> Change Color to be a struct rather than an enum

- examples/animation.rs
- examples/demo.rs
- examples/game-of-life.rs
- examples/gfx_demo.rs
- examples/image_demo.rs
- examples/message-box.rs
- examples/renderer-target.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- examples/resource_manager.rs
- examples/ttf_demo.rs
- examples/window-properties.rs
- src/sdl2/gfx/primitives.rs
- src/sdl2/image/mod.rs
- src/sdl2/messagebox.rs
- src/sdl2/mouse/mod.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
This is my initial attempt at separating the LoadTexture (from the image feature) from the rest of the renderer. A lot of the changes are just rustfmt doing it's business as I coded away. It addresses #630 
All tests pass, and all the examples run (the only example I could not run on my machine was the audio-queue-square-wave since it requires SDL2.0.4 and I have 2.0.0 but I did not change anything on the audio feature I am confident that it works. 
Pros of my current approach:
- The SDL image context is now required for loading images, which means that we will not accidentally try to load an image after this context has been dropped. 
- LoadImage is separate from the rendering functions which allows the user to create a ResourceManager that holds the ImageLoader (the sdl image context) …
> Split renderer

- src/sdl2/render.rs
This allows closures passed to `Canvas::with_texture_canvas()` to take ownership of values from the enclosing scope.
> Resolve #677 (change FnMut to FnOnce)

- examples/audio-capture-and-replay.rs
- src/sdl2/audio.rs
* Added open_capture method to AudioSubsystem
* Added example audio-capture-and-replay
> Support Audio Capture in AudioCallbacks

- src/sdl2/video.rs
> Made get/set_swap_interval take and return an enum instead of i32

- sdl2-sys/build.rs
These frameworks are necessary to link SDL2 into an iOS program.
https://github.com/spurious/SDL-mirror/blob/a4a9743a983dfccd6e7cc16fa3cb0f6d468041c1/configure.in#L3524-L3533
> Add link directives for iOS frameworks

- .travis.yml
- Cargo.toml
- README.md
- examples/game-of-life-unsafe-textures.rs
- src/sdl2/render.rs
cc @tanis2000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/angrylawyer/rust-sdl2/683)
> Add 'Unsafe textures' feature

- changelog.md
- src/sdl2/mixer/mod.rs
This is a solution to issue #696.
> Add Music::from_bytes() function

- examples/audio-squarewave.rs
This PR preemptively fixes the audio-squarewave.rs example from an eventual error when [the rust-lang issue on matching floating point literals](https://github.com/rust-lang/rust/issues/41620) is completed.
> Fix floating-point literal used in pattern in example

- changelog.md
- src/sdl2/mixer/mod.rs
Also deprecate the now-unnecessary channel(i32) function.
> Make mixer::Channel and mixer::Group fields public

- changelog.md
- examples/haptic.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/haptic.rs
- src/sdl2/joystick.rs
This updates the `which` properties of `ControllerDeviceAdded` and `JoyDeviceAdded` events to be `u32`s, as described in #713. This makes their types match the methods for opening controllers and joysticks.
It also adds documentation to differentiate between the now differing types of `which` values Controller and Joystick events contain, and updates the parameter names of joystick and controller methods to be more consistent about differentiating “joystick IDs” and “joystick indexes”.
fixes #713
> Friendlier ControllerDeviceAdded and JoyDeviceAdded `which` values

- Cargo.toml
The reason I'm asking for this change is simply that it makes it easier for a user to use a package which requires `c_vec` version 1.2 (like cairo-rs) and sdl.
otherwise, when using `Cargo`, the user will be faced with the following issue:
```
error: failed to select a version for `c_vec` (required by `sdl2`):
all possible versions conflict with previously selected versions of `c_vec`
version 1.2.0 in use by c_vec v1.2.0
possible versions to select: 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0
```
Looking at the history of c_vec, it looks to me that they keep backward compatibility from 1.0.x to 1.3. However, I'm not very familiar with rust to be 100% sure of that.
> Allow for more versions of c_vec to be used

- changelog.md
- src/sdl2/joystick.rs
Casing is inconsistent with other HatState variants.
> Fix HatState::Leftdown casing into HatState::LeftDown

- Cargo.toml
I was trying to run all examples and hit some issues:
- a couple of them were not defined on `Cargo.toml`
- another was missing `required-features` which resulted in not being able to be built
> Add missing examples & required features

- Cargo.toml
- sdl2-sys/Cargo.toml
- sdl2-sys/build.rs
This is a follow up on the unmerged PR693.
The build.rs file in sdl2-sys has been totally overhauled. The "bindgen" feature is now smart enough o use the headers directly from the source if "bundled" is specified. Likewise, the library is compiled dynamically or statically (and linked as well), whether or not the feature "static-link" is enabled.
* Still needs documentation in readme as of what these do
* Needs testing across **all** platforms, with at least the following features:
* vanilla
* "bundled"
* "static-link"
* "bundled,static-link"
* "static-link,pkg-config" (if possible)
* "pkg-config" (if possible)
* "bindgen" (if possible) 
* "bindgen,pkg-config" (if possible) 
Currently been tested on:
- iOS (not deemed possible, see later inthis thread)
PS: If someone has a clue of what's …
> Support "bundled", "bindgen" and opt-in static linking

- .travis.yml
- examples/gfx-demo.rs
Resolves https://github.com/Rust-SDL2/rust-sdl2/issues/722
While testing this I noticed there's an unused macro (Rust's warning) and removed that.
- Introduce a bug in an example
- Run `cargo build --examples --features "gfx image ttf mixer"`
- Note: `--examples` option was added on [cargo PR3901](https://github.com/rust-lang/cargo/pull/3901)
- Revert the bug
- Run it again
> Build examples on Travis

- changelog.md
- src/sdl2/pixels.rs
- src/sdl2/render.rs
This is just the probably simplest solution for #699.
> Add tuple conversions with From for Color #699

- .travis.yml
Fixes #734.
(Unfortunately, all mac rust nightly builds are failing today due to issues uploading the nightly last night, so this still won't be green until tomorrow.)
> Fix mac travis build

- src/sdl2/clipboard.rs
SDL_SetClipboardText returns 0 on success, not failure.  Before this
fix, calling set_clipboard_text successfully would generally return
Err("").
> Error checking fix for `ClipboardUtil::set_clipboard_text`

- src/sdl2/video.rs
Add SDL_GetWindowBordersSize() as `pub fn border_size(&self) -> (i32, i32, i32, i32)` to `Window`
> Add SDL_GetWindowBordersSize()

- src/sdl2/clipboard.rs
- src/sdl2/filesystem.rs
Namely SDL_GetBasePath and SDL_GetClipboardText.
For stupid reasons, we have to call SDL_GetClipboardText every frame, and we discovered a pretty bad memory leak if you HAPPENED to have large clipboard content.
There may be other errors of the same pattern, but I haven't looked for them.
> fix memory leaks on ClipboardUtil::clipboard_text() and filesystem::base_path()

- examples/mixer-demo.rs
The mixer demo is broken for sdl2_mixer 2.0.2 because Mix_OpenAudio must be called before other functions in the sdl2_mixer library.
https://bugs.archlinux.org/task/56303#comment163521
https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_11.html#SEC11
> Fix the mixer demo for sdl2_mixer 2.0.2

- src/sdl2/rect.rs
Looks like commit b00e8896 removed the existing `Hash` impls for `Rect` and `Point` (by accident, I assume), which broke some of my code that was using `HashMap<Point, T>` in many places.  This PR adds `Hash` impls back for `Rect` and `Point`.
> Add Hash impls for Point and Rect

- sdl2-sys/build.rs
Had to make a few small changes to the sdl2-sys build.rs to get linux-windows cross compilation working on my machine.
I'm not sure if outright disabling the GLES subsystem is acceptable but I know that by default, mingw doesn't come with GLES or EGL headers. So if you try building SDL from source without disabling it, it fails.
I noticed that SDL can provide it's own GLES headers but as far as I could tell they're only used if _MSC_VER is defined, and I figured defining that for a non-msvc target might be a bad idea.
> Allow sdl2-sys to build for windows-gnu target

- examples/joystick.rs
- src/sdl2/joystick.rs
This PR adds a `power_level` method to the `Joystick` type. The method’s signature looks like this:
```rust
pub fn power_level(&self) -> Result<PowerLevel, IntegerOrSdlError>
```
At this stage, due to limitations in SDL2 itself, this method only returns a useful value for XInput devices on Windows, but hopefully SDL2 will improve that in the future! On unsupported platforms, this will currently consistently return `Ok` wrapping `sdl2::joystick::PowerLevel::Unknown` with no error.
On a supported platform, it will return `Ok` wrapping one of `sdl2::joystick::PowerLevel::{Unknown, Empty, Low, Medium, Full, Wired}`, depending on the type and status of the controller. These values mirror those in the underlying SDL2 enum, discarding the “MAX” value which is not used (this appeared to be the …
> Expose Joystick power level

- src/sdl2/timer.rs
If the result of add_timer is unused, the timer will be dropped immediately and the callback won't fire. A small gotcha, and this change can save some debugging time.
> Add a #[must_use] directive to add_timer()

- src/sdl2/lib.rs
Make getting-started example copy-paste friendly by adding "extern crate sdl2;" line.
When I was starting to read the docs, the first thing I did was copy-paste this example into a file to play with it but without this line, it doesn't compile (easy enough to fix, but wanted to fix it at the source).
From reading the contributing guidelines, this appears to be small enough/documentation only, so I didn't think it required a changelog update.
> Make getting-started example copy-paste friendly

- README.md
- sdl2-sys/sdl_bindings.rs
- sdl2-sys/wrapper.h
- src/sdl2/video.rs
This includes Rust wrappers for SDL's Vulkan functions. I've also included an example program in the readme, much like the existing one for OpenGL.
edit by @Cobrand: Closes #784
> Vulkan support

- sdl2-sys/build.rs
Windows binaries don't embed library search paths, so tests were
failing for being unable to find sdl2.dll. This commit adds some
logic to copy that DLL into a known-good location.
> "Install" Windows dynamic libraries

- src/sdl2/audio.rs
I had an assert in `get_callback` and noticed when it failed the program segfaulted, this was due to the userdata here https://github.com/Thinkofname/rust-sdl2/commit/0ca64698e97776ef1754da97b4856bc6ef9190ad#diff-93048819a6101989491fb36a4efc59cbL639 being freed with uninitialized memory. This seemed like the safest way to fix it but there could be a better way.
The AudioStatus change is just something I saw when reading through, the use of transmute seemed a bit funny there and could introduce undefined behaviour in safe code.
> Audio safety fixes

- sdl2-sys/build.rs
- src/sdl2/event.rs
- src/sdl2/rect.rs
Currently, compilation fails on Windows when simultaneously using the 'bundled' and 'use-bindgen' feature. This is due to 2 separate problems:
1) The new vulkan support requires minimum of SDL version 2,0.8 but build script is still pulling 2.0.5, resulting in SDL_vulkan.h header not found.
2) Debug is not implemented for arrays whose size are too big - see issue #771. This is because Rust does not automatically provide Debug implementations for arrays whose size are > 32.
This pull request fixes both problems. Note that to fix the second problem, bindgen is configured to not generate #[derive(Debug)]. I'm not sure if this is the right way to fix this, but Debug wasn't really used in the public interface of rust-sdl2 anyway, except for Rect and Point. For this 2 structs, I manually …
> Fix compilation failure on Windows when using 'bundled' and 'use-bindgen' features

- README.md
- sdl2-sys/build.rs
Upgrading to SDL 2.0.9 broke static linking on windows-gnu because SDL's new HIDAPI code added a dependency on setupapi.dll. This was easily fixed by adding a line to sdl2-sys/build.rs.
I also added some notes to the README regarding static linking on Windows. To summarize:
- On the MSVC toolchain, you need to use `bundled` for `static-link` to work.
- On the GNU toolchain, you need some additional MinGW libraries.
> Fix and document static linking on Windows

- sdl2-sys/SDL2-2.0.9/include/SDL_config.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config.h.cmake
- sdl2-sys/SDL2-2.0.9/include/SDL_config.h.in
- sdl2-sys/SDL2-2.0.9/include/SDL_config_android.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_iphoneos.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_macosx.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_minimal.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_os2.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_pandora.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_psp.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_windows.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_winrt.h
- sdl2-sys/SDL2-2.0.9/include/SDL_config_wiz.h
Somehow the config headers got messed up when they were updated to SDL 2.0.9. The ones currently in the repo contain a Windows-specific SDL_config.h found in the zip containing the development libraries from libsdl.org, so maybe it comes from there.
I replaced that header with all the SDL_config* files from the SDL 2.0.9 tarball and now it builds fine on Linux and macOS when using the `use-bindgen` feature with the bundled headers.
> Fix `use-bindgen` feature on non-windows platforms

- sdl2-sys/Cargo.toml
- sdl2-sys/build.rs
This removes the dependency on the reqwest library and replaces it with calls to external tools (PowerShell on Windows and `curl` everywhere else) to download the SDL2 source when using the `bundled` feature. I've tested it on Windows 10; you probably want to give it a spin on Linux and MacOS before merging.
Closes #820
> Replace reqwest with calls to curl/powershell

- changelog.md
- examples/game-controller.rs
- examples/joystick.rs
- scripts/travis-install-sdl2.sh
- src/sdl2/controller.rs
- src/sdl2/joystick.rs
I added `sdl2::controller::set_rumble` and `sdl2::joystick::set_rumble`, wrappers for the two new (since SDL 2.0.9) rumble functions `SDL_GameControllerRumble` and `SDL_JoystickRumble` respectively.
The `game-controller` and `joystick` examples were also extended to test them a little.
> Add wrappers for SDL 2.0.9 rumble functions

- Cargo.toml
- examples/cursor.rs
- examples/image-demo.rs
- examples/message-box.rs
- examples/mixer-demo.rs
- examples/resource-manager.rs
- examples/ttf-demo.rs
- src/sdl2/image/mod.rs
- src/sdl2/keyboard/mod.rs
- src/sdl2/messagebox.rs
- src/sdl2/mixer/mod.rs
- src/sdl2/ttf/font.rs
- src/sdl2/ttf/mod.rs
This PR replaces #772, so most notes in that PR are applicable to this one.
Note that this slightly changes the names of constants that users will interact with, for example;
* `MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT` is now `MessageBoxButtonFlag::RETURNKEY_DEFAULT`
* `INIT_PNG` is now `InitFlag::PNG`
* etc.
> Update to bitflags 1.* from 0.7

- Cargo.toml
- src/sdl2/pixels.rs
Rand 0.6 no longer includes the [`Rand`](https://docs.rs/rand/0.5.5/rand/trait.Rand.html) trait; it was replaced with the `Standard` [`rand::distribution`](https://docs.rs/rand/0.6.1/rand/distributions/index.html#the-standard-distribution).
As per the docs, implementing `Distribution<T> for Standard` allows `Rng::gen()` and `random()` to generate the given type (in this case, `Color`s), so (as far as I can tell) this update won't change the interface of pixles.rs in any meaningful way.
> Update Rand to 0.6.* from 0.5.*

- examples/animation.rs
- examples/audio-capture-and-replay.rs
- examples/audio-queue-squarewave.rs
- examples/audio-squarewave.rs
- examples/audio-wav.rs
- examples/audio-whitenoise.rs
- examples/cursor.rs
- examples/demo.rs
- examples/game-controller.rs
- examples/game-of-life-unsafe-textures.rs
- examples/game-of-life.rs
- examples/gfx-demo.rs
- examples/haptic.rs
- examples/image-demo.rs
- examples/joystick.rs
- examples/keyboard-state.rs
- examples/message-box.rs
- examples/mixer-demo.rs
- examples/mouse-state.rs
- examples/no-renderer.rs
- examples/relative-mouse-state.rs
- examples/renderer-target.rs
- examples/renderer-texture.rs
- examples/renderer-yuv.rs
- examples/resource-manager.rs
- examples/ttf-demo.rs
- examples/window-properties.rs
Part of #836 
This PR modifies all the examples in the `examples/` folder to use more idiomatic Rust error handling code. This PR is already quite big with quite a few (hopefully small and easy to review) changes, so converting the examples in the docs will be a separate PR later.
I manually went through and ran `cargo run` for each example, so hopefully they all compile and CI will pass.
Everything should still work exactly the same. This PR isn't meant to change any functionality. Just updating to the latest idioms.
Some notes:
* All calls to `unwrap()` are completely gone from all examples
* Majority of those calls are replaced with the `?` operator where possible
* Some calls could not be removed without a breaking change to the specs API, so `expect()` was used to keep this PR easy …
> Improved Exaple Error Handling: Replaced all calls to unwrap() in examples with either the ? operator or expect()

- sdl2-sys/build.rs
Fixes unresolved externals:
```
= note:    Creating library C:\Code\0-Research\r64emu\target\debug\deps\r64emu-31b08ffa115962a8.lib and object C:\Code\0-Research\r64emu\target\debug\deps\r64emu-31b08ffa115962a8.exp
libsdl2_sys-dcf2e13e2a4771aa.rlib(SDL_windowsevents.obj) : error LNK2019: unresolved external symbol __imp_DragQueryFileW referenced in function WIN_WindowProc
libsdl2_sys-dcf2e13e2a4771aa.rlib(SDL_windowsevents.obj) : error LNK2019: unresolved external symbol __imp_DragFinish referenced in function WIN_WindowProc
libsdl2_sys-dcf2e13e2a4771aa.rlib(SDL_windowsevents.obj) : error LNK2019: unresolved external symbol __imp_ExtractIconExW referenced in function SDL_RegisterApp_REAL
libsdl2_sys-dcf2e13e2a4771aa.rlib(SDL_sysfilesystem.obj) : error LNK2019: unresolved external symbol …
```
> Add missing shell32 to static link libraries on Windows

- src/sdl2/event.rs
The only thing keeping these from auto deriving is the `User` variant's `data1` and `data2` `*mut c_void` fields. Given that those fields are opaque "do whatever you want and ensure your own guarantees" things that aren't necessarily actual pointers and require unsafe to use at all, I don't _think_ having `Event` be `Send`+`Send` is particularly problematic.
This is stemming from https://github.com/michaelfairley/rust-imgui-sdl2/issues/5, where someone wants render their GUI in a separate specs system (which might be running in a different thread), and the GUI library does some processing on `Event`s, and it feels like it should be fine to `Send` them.
> Mark Event as Send+Sync

- src/sdl2/rect.rs
Without this, newer rustc versions complain with the error:
> access to extern crates through prelude is experimental (see issue #44660)
Other files in this repository also use the absolute name of entities from `std`, so I imagine this was just an oversight.
> Use ::std instead of just std in rect.rs

- sdl2-sys/build.rs
It can't find `SDL2main` or `SDL2` when trying to statically link with homebrew libs.
> Homebrew packages are called libSDL2main and libSDL2

- build.rs
- sdl2-sys/build.rs
Hi,
this patch fixes linking on OpenBSD. All the examples now work.
> Fix linking on OpenBSD

- src/sdl2/video.rs
Signed-off-by: german gomez <germangb42@gmail.com>
> Window opacity methods

- README.md
- changelog.md
As of #867, this create no longer builds with `libsdl v2.0.4`.
> *This function is available since SDL 2.0.5.*
> https://wiki.libsdl.org/SDL_GetWindowOpacity
(I didn't realize at the time :sweat_smile:  I updated the README to reflect it)
> Update minimum SDL2 version in README

- sdl2-sys/build.rs
- src/sdl2/ttf/font.rs
This commit fixes #879
The `run_command()` function in the build script improperly formats the arguments given to it by `download_to()`. This commit changes `download_to()` so it structures the arguments correctly before passing it to `run_command()` with a call to `format!()`.
> Use `format!()` for powershell arguments in `download_to`

- src/sdl2/ttf/font.rs
The namespacing workaround required for `bitflags!` is no longer required as per https://github.com/bitflags/bitflags/issues/39. Resolves #880
> Fix obsolete bitflags_rs absolute paths workaround

- src/sdl2/audio.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
- src/sdl2/keyboard/mod.rs
- src/sdl2/mouse/mod.rs
- src/sdl2/mouse/relative.rs
- src/sdl2/pixels.rs
- src/sdl2/rect.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
This will remove redundant field names as described in it's [lint](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names)
> Remove redundant field names

- sdl2-sys/build.rs
This PR simply allows compiling any project using SDL2 with cargo web. It's just a matter of avoiding linking the SDL2 library as the port from emscripten will be used instead.
> Allows compiling with emscripten

- changelog.md
- src/sdl2/pixels.rs
see issue #840
This commit implements the `TryFrom<PixelFormatEnum>` trait for `PixelFormat`.
There isn't any test yet, since I wasn't sure wich way you would like to go about it
> Conversion from PixelFormatEnum to PixelFormat

- .travis.yml
Compiling `SDL2_ttf`  on Ubuntu in Travis CI requires `libGL.so`, which is included in `libgl1-mesa-dev`. Refer to https://discourse.libsdl.org/t/cross-compiling-sdl-ttf/18773.
This patch will resolve the recent issues of pull requests with the Travis CI check: [Build #1534](https://travis-ci.org/Rust-SDL2/rust-sdl2/builds/562923003), [#1535](https://travis-ci.org/Rust-SDL2/rust-sdl2/builds/569402827), ..., [#1542](https://travis-ci.org/Rust-SDL2/rust-sdl2/builds/577492109).
> Install libgl1-mesa-dev when testing with Travis CI

- src/sdl2/joystick.rs
- src/sdl2/timer.rs
The Logitech F310 gamepad has a direction pad that must have no central pivot point or something - you can press in the middle of the d-pad and it will register all four hat switches at the same time. When it's set to Xinput mode, the hat state reported by SDL2 is not in rust-sdl2's HatState enum. Interestingly, DirectInput doesn't do this, and the third party xinput adapter for MacOS doesn't do this either.
Also I added some missing `dyn` keywords because in recent versions of Rust, that's warn by default.
> Fix for panic upon invalid hat state reported by xinput driver

- src/sdl2/event.rs
- tests/events.rs
Rebased version of @ebarnard's https://github.com/Rust-SDL2/rust-sdl2/pull/748:
> EventSender does not keep the event subsystem alive and its functions return an error if the event subsystem has been shut down.
> 
> Closes #747
> EventSubsystem::push_event should be callable from non-main threads.

- src/sdl2/audio.rs
- src/sdl2/event.rs
- src/sdl2/rect.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
`core::mem::uninitialized` is deprecated in favor of the safer/more explicit `core::mem::MaybeUninit` wrapper type which is stable as of Rust 1.36. This PR replaces all of the uses of `uninitialized` with `MaybeUninit`.
One thing to note is that this will break dependents who target older stable versions of Rust. The README states that this project targets current stable so I doubt that should be much of an issue.
> Replace uses of deprecated mem::uninitialized with mem::MaybeUninit

- sdl2-sys/build.rs
Reverts a731b12f09015eab9486f7a8b0a90896f5d295a0 to fix #883. Have tested on macOS with both features on and everything appears to build and work fine :)
> Fix for macOS with "bundled" and "static-link" features 

- build.rs
Apply the linking fix of OpenBSD to FreeBSD, else it will not find system wide SDL2.
> Fix linking on FreeBSD

- src/sdl2/audio.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/haptic.rs
- src/sdl2/joystick.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/sdl.rs
- src/sdl2/surface.rs
- src/sdl2/timer.rs
- src/sdl2/video.rs
I was taking a stab at another issue and noticed there were a lot of compiler warnings in the way - I've updated them to compile cleanly now.
There were 3 different types of warnings that I fixed:
- `uint8_t` and `uint32_t` are deprecated and were changed to the builtin `u8` or `u32`, respectively
- The `try!` macro is deprecated and was replaced by the `?` operator
- There were 2 field accesses in tests from `src/sdl2/event.rs` that were unnecessarily wrapped in `unsafe` blocks, which have been simplified
> Clean up compiler warnings

- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/hint.rs
- src/sdl2/joystick.rs
- src/sdl2/lib.rs
- src/sdl2/mouse/mod.rs
- src/sdl2/pixels.rs
- src/sdl2/rect.rs
- src/sdl2/render.rs
- src/sdl2/sdl.rs
- src/sdl2/surface.rs
- src/sdl2/timer.rs
- src/sdl2/video.rs
Following up on #919, I fixed up the warnings from `clippy` lints as well.
- A lot of methods on "trivially copyable" small structs/enums had `self` by reference rather than value, which is less efficient. They can still be called the same way when taken by value.
- A few uses of unsafe `mem::transmute` could be replaced by safe `as` casts
- The `subsystem` macro actually implements the `Clone` trait rather than just a method named `clone`
- `clippy` is now an official component, so the `clippy::` namespace can be used instead of the `#[cfg_attr(feature = "cargo-clippy",  ...)]` guard
- Plus a few miscellaneous idiomatic style fixes
> Clean up clippy warnings

- sdl2-sys/build.rs
Remove cfg!(target_os="x") from build.rs
using the cfg macro breaks cross compilation. This is because the cfg
macro gets evaluated during compile time of the binary getting built. In
the case of build.rs, it gets built into it's own binary targeting the
local machine. (Which then gets run to evaluate build rules for the
primary project binary). So somewhat confusingly, the cfg(target_os..)
evaluates differently in build.rs than the rest of the project in the
case of cross compilation. Particularly for SDL, this is important for
targeting emscripten. The current build.rs breaks when trying to compile
for the web.
> Fix cross compilation

- src/sdl2/audio.rs
With the current callback function signatures it'll be both easier to
use than AudioSpec.silence and it's correct in all cases.
Closes issue #934.
> Provide AudioFormatNum.SILENCE constant

- sdl2-sys/build.rs
- sdl2-sys/patches/SDL2-2.0.9-CMakeLists.txt.patch
When building on Windows with Visual Studio Build Tools 2019 using the `bundled` feature, I get this error:
```error LNK2019: unresolved external symbol memset referenced in function SDL_vsnprintf_REAL```
This [Stack Overflow](https://stackoverflow.com/questions/58288692/cant-build-solution-in-release-mode-for-sdl-library-on-vs-2019) provides a solution that works if I manually patch `CMakeLists.txt`.
This PR leverages the patching functionality of the `bundled` feature to automatically make this change as part of the build.
> Fix error building on Windows w/ 2019 Build Tools.

- Cargo.toml
- src/sdl2/audio.rs
- src/sdl2/event.rs
- src/sdl2/gfx/primitives.rs
- src/sdl2/lib.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
I noticed that this crate uses only two features of `num-traits`:
1. `num::FromPrimitive` - used to convert raw integers to Rust enums. Is using an external library for this really necessary?
2. `num::ToPrimitive` - used to convert colors `isize` values to colors, replaced it with `std::convert::TryFrom`.
2. `num::traits::cast` - used in literally only one place, so I replaced it with `std::convert::TryInto`.
The `FromPrimitive` trait is located in the `num-traits` crate, so by depending on it instead of all of `num` I managed to reduce the total number of dependencies from 25 to 18. Also I took the opportunity and upgraded it from v0.1 to v0.2.
If using `num-traits` for `int <-> enum` conversions is an overkill in your opinion, I can also open a PR to remove it from dependencies …
>  Use the num-traits crate directly instead of num 

- sdl2-sys/build.rs
- src/sdl2/gfx/framerate.rs
- src/sdl2/image/mod.rs
- src/sdl2/mixer/mod.rs
- src/sdl2/ttf/context.rs
- src/sdl2/ttf/font.rs
When compiling the project, different compiler warnings show up:
```
$ cargo build --features "bundled"            
[...]
warning: variable does not need to be mutable
--> sdl2-sys/build.rs:223:17
|
223 |             let mut dst_file = fs::File::create(&file_path)
|                 ----^^^^^^^^
|                 |
|                 help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
[...]
```
and
```
$ cargo build --features "gfx image ttf mixer"
[...]
warning: unused doc comment
--> src/sdl2/image/mod.rs:34:1
|
34 | / /// InitFlags are passed to init() to control which subsystem
35 | | /// functionality to load.
| |__________________________^
36 | / bitflags! {
37 | |     pub struct InitFlag : u32 {
38 | |         const JPG  = image::IMG_InitFlags_IMG_INIT_JPG as u32; …
```
> Fix compiler warnings

- src/sdl2/audio.rs
- src/sdl2/joystick.rs
- src/sdl2/macros.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/video.rs
Right now it's not possible to create a color in a constant context using: https://github.com/Rust-SDL2/rust-sdl2/blob/e865c8f4643e7f333c94e2cff8abd9497736ca4b/src/sdl2/pixels.rs#L103-L107
This PR changes functions marked with `#[inline]` to be constant, where possible.
What do you think?
> Constify some inlined functions

- sdl2-sys/patches/SDL2-2.0.9-CMakeLists.txt.patch
This fixes #953 (regression of #951). I tested with x86_64-pc-windows-msvc (VS2019) and x86_64-pc-windows-gnu and both seem to work now. It should also work with VS2017 but I can't test it.
> Fix build with mingw

- Cargo.toml
- src/sdl2/audio.rs
- src/sdl2/event.rs
- src/sdl2/lib.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
I replaced every occurrence of `FromPrimitive` with `TryFrom` with `()` as the error type.
I also noticed a recurring pattern of casting C enums to uints and then converting uints to Rust enums, perhaps this can be avoided by adding `From`/`TryFrom` traits for converting C enums directly to Rust ones? And some `TryFrom` implementations can be converted to `From` by assuming default values, e.g. `PixelFormatEnum::Unknown` when the pixel format is unknown.
> Remove num-traits altogether

- sdl2-sys/build.rs
- sdl2-sys/patches/SDL2-2.0.10-CMakeLists.txt.patch
Fixes https://github.com/Rust-SDL2/rust-sdl2/issues/958
> Fix errors building on Windows with bundled #958

- src/sdl2/event.rs
Some were i32, others (for mouse) were u32. It cannot be negative because it's not an error variable, so it's always positive and thus safe to use u32 here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rust-sdl2/rust-sdl2/955)
> Joy/controller Events all have `which` member of type u32

- src/sdl2/pixels.rs
This adds an "invert()" method that returns the inverse of the `Color` being used.  It also adds commonly named colors to the `Color` implementation, so that applications can call on these rather than having to create their own constants.
> Added invert method for color, and added common color names.

- Cargo.toml
- README.md
- changelog.md
- examples/raw-window-handle-with-wgpu/main.rs
- examples/raw-window-handle-with-wgpu/shader.frag
- examples/raw-window-handle-with-wgpu/shader.vert
- src/sdl2/lib.rs
- src/sdl2/raw_window_handle.rs
- src/sdl2/video.rs
- tests/raw_window_handle.rs
Taking off from #910: @Lokathor provided some system-specific bindings and I've plucked out the necessary stuff to make this run on macOS, linux, and windows. This definitely runs on macOS, but I was unable to procure linux and windows machines to verify support there. I'm confident it "should work", though.
> Support for raw-window-handle

- README.md
- changelog.md
- sdl2-sys/build.rs
In order to facilitate using the includes provided/found by `sdl2-sys` in other `*-sys` crates, I have added print statements which set the "include" key to the path to the include folder that has either been provided or found.
This can be accessed through the environment variable `DEP_SDL2_INCLUDE` in all crate build scripts which _directly_ depend on `sdl2-sys`, transitives are not affected. 
If there are multiple include directories, they are separated by a `:`.
A use case can be found [here](https://github.com/BVE-Reborn/bve-reborn/blob/b3114b5a0a77ce779f8880b41c2c1f83b314b4d6/bve-rex-sys/build.rs#L132) where I must pass the header directory to `cc` to build c++ code which depends on SDL2.
I have tried to make as few changes as possible to the build script, however I did make two …
> Print Out SDL2 Include Directory in sdl2-sys Build Script

- src/sdl2/video.rs
Allows graphics drivers to run with reduced overhead.
[https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_no_error.txt](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_no_error.txt)
>
With this extension enabled any behavior that generates a GL error will
have undefined behavior.  The reason this extension exists is performance
can be increased and power usage decreased.  When this mode is used, a GL
driver can have undefined behavior where it would have generated a GL error
without this extension.  This could include application termination.  In
general this extension should be used after you have verified all the GL
errors are removed, and an application is not the kind that would check
for GL errors and adjust behavior based on those errors.
I hope this file is all I …
> Add support for SDL_GL_CONTEXT_NO_ERROR.

- src/sdl2/raw_window_handle.rs
On certain systems not doing this will cause a "Couldn't get SDL window info: Application not compiled with SDL 2.0" error.
> Fix version detection by calling GetVersion before GetWindowWMInfo

- examples/mixer-demo.rs
- src/sdl2/mixer/mod.rs
This basically provides an API to access Mix_QuickLoad_WAV and
Mix_QuickLoad_RAW with one caveat – thie API takes ownership of the
buffers, while Mix_QuickLoad_* functions don't. Since Rust-SDL2 wraps
Mix_Chunks in its own structure with its own buffer ownership flag it's
easy to work around that and deallocate the buffer when Chunk is
dropped.
There are few design considerations here:
* Taking ownership of the buffer. I couldn't come up with a way to
get a Chunk based on a buffer while still keeping the code safe and
making sure that as long as Chunk is alive the buffer is also alive
*and* not making the change be terribly involved and disruptive
* What's the best way to take an ownership of a buffer passed as a
parameter? I came up with Box<[T]> as it seems universal enough,
but I …
> Provide memory buffer -> mixer Chunk conversion methods

- src/sdl2/mixer/mod.rs
Now the following line would compile and load the opus dll files (which are already included in the SDL2 downloads, and the bindings already included it):
mixer::init(mixer::InitFlag::OPUS)
Tested, works,  and I'm using opus music files in my program now.
> Feature: Added support for loading Opus format sound files in mixer

- sdl2-sys/build.rs
- sdl2-sys/patches/SDL2-2.0.10-sndio-shared-linux.patch
Current SDL2 versions have a bug: somebody forgot to declare
SNDIO_SHARED in CMakeLists.txt so even if the support for dynamically
loading sndio is fully implemented (like in all other audio backends),
it is never activated.
This in turns means that supporting sndio always requires linking at
link-time against libsndio, which in turns creates binaries that require
libsndio on the target system to even start (even if no audio support
is required, or if other audio options like PulseAudio or Jack are
available).
build.rs had a workaround for this bug: it always linked against
libsndio, but this created binaries with this dependency.
I've opened a bug upstream:
https://bugzilla.libsdl.org/show_bug.cgi?id=5105
and I'm including the one-line patch in this PR so that we can fix
rust-sdl2 …
> Fix build on Linux to support sndio dynamic loading

- Cargo.toml
This PR will make the docs.rs generated documentation complete. No need to host your documentation anymore.
Also, it'd be very nice to expand the documentation to make life of users a bit easier (I had a really hard time with textures...). Adding more code examples or explaining a bit more what a function/type is for. I can help for that if needed. Don't forget that you can use the "no_run" attribute on code blocks to prevent having the full run. It also has the advantage to check that the examples are up-to-date.
> Enable features for docs.rs

- src/sdl2/gesture.rs
- src/sdl2/lib.rs
`gesture` module is an empty public module, and it was empty since 2015 (#295)
`macros` is a module that contains private utility macros, there's no point in making it public
> Remove empty `gesture` module, hide `macros` module

- Cargo.toml
- examples/raw-window-handle-with-wgpu/main.rs
- examples/raw-window-handle-with-wgpu/shader.vert
* Remove WindowWrapper since wgpu now uses raw-window-handle correctly on OSX which also lets us remove the objc dependency
* Add futures dependency to handle parts of the wgpu API that are now asynchronous
* Flip y coords in vertex shader to keep triangle oriented the same way since wgpu flipped their y-axis
* Fix various other errors resulting from breaking API changes in wgpu
I'm new to Rust so please review accordingly. The only thing I'm really unsure of is if I picked the most idiomatic way to handle the `Result` returned by `swap_chain.get_next_texture()` since the `TimeOut` error doesn't implement `Display`.
> Update raw-window-handle-with-wgpu example to use wgpu 0.5

- src/sdl2/event.rs
I had to write those helpers into my code so I think it's worth adding them upstream because I'm pretty sure I'm not the only one having some usage for them. :)
> Add helper functions for Event

- src/sdl2/event.rs
> Add WindowEvent::is_same_kind_as

- Cargo.toml
This should show the README on crates.io, which currently does not display anything useful
> Link Readme for crates.io

- .github/workflows/vcpkg.yml
- Cargo.toml
- README.md
- changelog.md
- sdl2-sys/Cargo.toml
- sdl2-sys/build.rs
I'm not sure if you are interested in merging this but I thought it might be useful. It allows building static binaries with dynamic libc/crt on macOS, Linux and Windows. (There are other configurations available on Windows - fully static and fully dynamic.) The workflow is the same on each of the three operating systems above. This should be enough to get it going in a rust-sdl2 checkout:
```
cargo install cargo-vcpkg
cargo vcpkg build
cargo test --features "use-vcpkg static-link gfx image ttf mixer"
```
> support linking to libraries from a vcpkg installation

- sdl2-sys/Cargo.toml
- sdl2-sys/build.rs
Resolves this issue https://github.com/Kethku/neovide/issues/306
> Patch allow gcc10

- src/sdl2/audio.rs
Fixes a use-after-free in `AudioDevice::open`, which occurs when
selecting a particular device by name (as opposed to using a default
device).
Specifically, when extracting a C-style string pointer from a
`Option<CString>`, the option was consumed, its contents turned into a
pointer, and the original `CString` dropped. After that the C-style
string pointer is dangling, as its backing rust CString has been freed.
To fix this, the CString must be kept alive, which is achieved by simply
creating an intermediary `Option<&CString>`, and consuming that.
When trying to open an audio recording device called `HD Webcam C615 Analog Mono` on my machine:
* `device_ptr` points to `@\xf4~UUU\x00\x00m C615 Analog Mono` (which when interpreted as a null-terminated C string is actually just `@\xf4~UUU`), …
> audio: fix device name use-after-free in AudioDevice::open

- src/sdl2/image/mod.rs
load assets from buffer, eg.
https://github.com/netcan/AnimalChess/blob/master/bin/src/gui.rs#L53
> add load_texture_bytes interface for load texture from buffer

- src/sdl2/macros.rs
- src/sdl2/rect.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/surface.rs
- src/sdl2/ttf/font.rs
- src/sdl2/video.rs
Hi folks
In a recent revision of rust-sdl2 my art tool ( https://github.com/danielrh/stamps ) was beginning to get increasingly difficult to track undefined behavior, especially on release.
After trying everything I knew of with the SDL 2.0.10 upgrade--I determined it was likely to be in the rust layer.
So I bisected the code and found the offending diff was a9893f0c0d42f012c312280ed3b0a785fcf9abcc which returned the address of a local variable when getting the raw data out of a rect
I've attached a reverting change here which restores my program to normal operations
> revert undefined behavior introduction (recommended by clippy?)

- changelog.md
- sdl2-sys/build.rs
- sdl2-sys/patches/SDL2-2.0.12-metal-detection-macos-ios.patch
This fixes #1028 by patching in a change that is upstreamed but not in 2.0.12
https://hg.libsdl.org/SDL/rev/e7828d3a7576
> Add SDL2 patch to fix metal detection for macOS/iOS

- sdl2-sys/build.rs
This change was missing in my previous PR #1030. It fixes these link errors:
```
"_OBJC_CLASS_$_MTLSamplerDescriptor", referenced from:
objc-class-ref in libsdl2_sys-c107b63fb2e1f32f.rlib(SDL_render_metal.m.o)
"_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
objc-class-ref in libsdl2_sys-c107b63fb2e1f32f.rlib(SDL_render_metal.m.o)
"_OBJC_CLASS_$_MTLRenderPassDescriptor", referenced from:
objc-class-ref in libsdl2_sys-c107b63fb2e1f32f.rlib(SDL_render_metal.m.o)
"_OBJC_CLASS_$_MTLVertexDescriptor", referenced from:
objc-class-ref in libsdl2_sys-c107b63fb2e1f32f.rlib(SDL_render_metal.m.o)
"_OBJC_CLASS_$_MTLRenderPipelineDescriptor", referenced from:
objc-class-ref in libsdl2_sys-c107b63fb2e1f32f.rlib(SDL_render_metal.m.o)
"_MTLCreateSystemDefaultDevice", referenced from: …
```
> Add metal framework

- changelog.md
- src/sdl2/timer.rs
Hi there,
Currently, the [ticks](https://docs.rs/sdl2/0.34.3/sdl2/struct.TimerSubsystem.html#method.ticks) method requires a `&mut self`, which this PR downgrades to a `&self`.
Please let me know if I've made a mistake in my understanding here. I _think_ `&self` should be fairly benign; AFAIK `ticks` doesn't do anything mutable under the hood.
What motivated this change is I can't check the elapsed `ticks` while I have a living `Timer` object due to the borrow checker. If I have missed a good reason this function is marked as mutable then please let me know.
> Changed ticks function from `&mut self` to `&self`.

- src/sdl2/audio.rs
- src/sdl2/clipboard.rs
- src/sdl2/controller.rs
- src/sdl2/cpuinfo.rs
- src/sdl2/event.rs
- src/sdl2/filesystem.rs
- src/sdl2/haptic.rs
- src/sdl2/hint.rs
- src/sdl2/image/mod.rs
- src/sdl2/joystick.rs
- src/sdl2/keyboard/keycode.rs
- src/sdl2/keyboard/mod.rs
- src/sdl2/keyboard/scancode.rs
- src/sdl2/log.rs
- src/sdl2/messagebox.rs
- src/sdl2/mixer/mod.rs
- src/sdl2/mouse/mod.rs
- src/sdl2/mouse/relative.rs
- src/sdl2/pixels.rs
- src/sdl2/raw_window_handle.rs
- src/sdl2/rect.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/sdl.rs
- src/sdl2/surface.rs
- src/sdl2/timer.rs
- src/sdl2/touch.rs
- src/sdl2/version.rs
- src/sdl2/video.rs
Hi, `doc(alias = "...")` just got released (more info about it [here](https://blog.guillaume-gomez.fr/articles/2020-12-04+doc%28alias%29+is+stable+and+it%27s+gonna+be+super+useful%21)) and I think it'd be very useful for this crate (I had issues finding what I was looking for more than once).
One thing to note: I added aliases for drop methods too, not sure if you want to keep them?
Little bonus: I used this python script to generate the attributes:
```python
import os
def is_valid_name(s):
for c in s:
if not c.isalnum() and c != '_':
return False
return True
def add_parts(path):
print("=> Updating '{}'".format(path))
with open(path, 'r') as f:
content = f.read().split('\n')
x = 0
while x < len(content):
clean = content[x].lstrip()
if not clean.startswith("pub fn") and not …
```
> Add doc aliases for C equivalents

- src/sdl2/event.rs
Closes #1023.
The new function enables to use an event watcher in a safe, user-friendly way.  We can call `EventSubsystem::add_event_watch` with a closure parameter as a callback to listen to the events.  The callback is automatically disabled when dropped.
When I wrote the code I largely referenced `AudioDevice::open`, `AudioSpecDesired::convert_to_ll` and `audio_callback_marshall` in `src/audio.rs`.  Great thanks to them.
Concerns:
* I'm not sure about the trait bounds and lifetimes.  Is it correct?  Also, the function may be called in multiple threads.  Is it desired to add `Send` or `Sync` as additional bounds?  (I'm not quite proficient at unsafe Rust, sorry)
* Is the "drop-to-disable" design good?
> Add wrapper for SDL_AddEventWatch and SDL_DelEventWatch

- src/sdl2/controller.rs
- src/sdl2/filesystem.rs
- src/sdl2/messagebox.rs
- src/sdl2/render.rs
- src/sdl2/ttf/font.rs
- src/sdl2/video.rs
Currently the error types that do exist in rust-sdl2 do not derive `Clone` which is inconvenient and not idiomatic rust. This pull request adds `Clone` as a derive for all error types defined (that I found at least).
> Added `Clone` to error types

- src/sdl2/render.rs
I added docstring for sdl2::render::BlendMode, based on https://wiki.libsdl.org/SDL_BlendMode
> Add docstring for sdl2::render::BlendMode

- .gitattributes
- changelog.md
This fixes an issue where the *.patch files get windows line endings
when checked out on windows, which breaks the bundled build when
building from git directly.
> rust-sdl2: Force unix line-endings for patches

- changelog.md
- sdl2-sys/build.rs
sdl2-sys was hardcoding the bundled build as a release build,
unconditionally for a long time.  This can cause problems however if an
upstream link of a binary is mixing C++ libraries that mix debug and non
debug builds, or so at least I'm led to believe for static builds.
> Debug builds

- src/sdl2/audio.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
- src/sdl2/messagebox.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/surface.rs
Rust 1.51 warns if panic!() is used without a string literal argument, and notes that this use will break in Rust 2021.
While here, also silence warnings about unneeded semi-colons.
> Silence warnings: string literals for panic!(), unneeded semicolons.

- sdl2-sys/build.rs
Upstream SDL2 will include _fltused in the libary artifact as a
__declspec(selectany) symbol.  This seems to cause problems however with
a definition already coming from the top-most rust link, as it already
gets defined elsewhere when building statically.
Rather than patching the upstream codebase with another patch, just
specify this flag in all cases as we don't require it in any of our rust
builds.
> sdl2-sys: Skip defining _fltused

- sdl2-sys/build.rs
- sdl2-sys/patches/SDL2-2.0.12-vs2019-intrinsics.patch
When building for "bundled" dynamic library on Windows, VS2019
encounters a link error as it is generating an intrinsic for memset but
the cmake build misses linking in the code for it.
Fix by cherrypicking upstream patch that works around the problem by
telling the compiler to generate actual function calls to it.
https://github.com/libsdl-org/SDL/issues/3865
> rust-sdl2: cherry pick vs2019 intrisics fix

- Cargo.toml
- sdl2-sys/Cargo.toml
vcpkg has been updated to fix the link ordering of the brotli libraries.
This means that vcpkg rev can now point at upstream again. Version
a267ab1 is current HEAD.
> Point at upstream vcpkg rev again

- changelog.md
- sdl2-sys/build.rs
Broke non-"static-link" builds on Windows when using "bundled" and non
release builds.
Closes #1088
> Revert "Allow bundled debug build (#1081)"

- sdl2-sys/build.rs
Fixed by staging dll in deps directory.
This is required for running comment examples as tests, which otherwise
don't seem to be picking up the dll in library path when it is only
dropped in the top most target_path.
Fixes
```
failures:
src/sdl2\event.rs - event::EventSender::push_custom_event (line 2874)
src/sdl2\event.rs - event::crate::EventSubsystem::add_event_watch (line 244)
src/sdl2\event.rs - event::crate::EventSubsystem::push_custom_event (line 203)
src/sdl2\event.rs - event::crate::EventSubsystem::register_event (line 135)
src/sdl2\rect.rs - rect::Rect::has_intersection (line 482)
src/sdl2\rect.rs - rect::Rect::intersection (line 504)
src/sdl2\rect.rs - rect::Rect::union (line 536)
```
when running `cargo test --features bundled` on Windows.
> Fix windows bundled example tests

- src/sdl2/audio.rs
This commit rewrites AudioCVT::convert to bounce the audio buffer into a
an SDL2 heap allocation, rather than trying to reuse the rust heap
buffer.  This is critical, as the underlying library warns internally
that the buffer may be reallocated, breaking configurations where
the library is not using the same heap as rust.
The underlying implementation also notes that the underlying buffer may
be transparently resized to larger than the output as part of the
transformations, so relying on the buffer being capacity() bytes long to
ensure the buffer is not re-allocated is a broken assumption.
Closes #1096
> Bounce through SDL2 heap in AudioCVT::convert

- .github/workflows/CI.yml
Add [static-link, dynamic] X [debug, release] builds of windows-latest "bundled" to CI.
> Add Windows bundled builds to CI

- src/sdl2/audio.rs
Update to reflect the surface interface and remove the bits about
conversion in place which are now out of date.
This also removes the note about buffer overflows in issue #270. Looking
back, the understanding was that the buffer wouldn't get reallocated,
and this is evident even in the sample C code used there.
> Update doc for AudioCVT::convert

- src/sdl2/video.rs
Linux and MacOS will make sure your window fits in the available space but Windows instead makes a window go under the taskbar. Use `SDL_GetDisplayUsableBounds` to avoid this.
> Added binding for SDL_GetDisplayUsableBounds.

- sdl2-sys/build.rs
Just like Windows, we should be copying the dynamic library to the
target directory and deps directory.  Otherwise, execution may fail,
or, more likely, silently pick up the system libSDL2 and not the
"bundled" one as asked.
This is evident when trying to run tests on a system with the libsdl2
package uninstalled, where all the example tests fail unless they pick
up the system .so.
> Copy non-Windows dynamic libs and symlinks to output

- .github/workflows/CI.yml
Expand Linux "bundled" testing to also cover release and static
variants.  Has the added benefit that this testing doesn't accidentally
see the libsdl packages that were installed as part of the pkg-config
testing.
While here, try enabling for macos as well to gather coverage for it.
> Expand bundled testing to linux and macos

- README.md
Update the rev given for vcpkg in the README to point at the same rev
used for rust-sdl2 testing.
> Update vcpkg rev in docs

- sdl2-sys/Cargo.toml
Since the most common crates have already moved to v1 of cfg-if, the current version makes sdl2 introduce a new version.
(tested on a monorepo with more than a 100deps).
> Update cfg-if to 1.0

- Cargo.toml
- README.md
Something happened that broke the `vcpkg.exe install` invocation for
sdl2 on Windows when using github actions with `windows-latest`.
I have not been able to determine what is actually causing the break,
however updating to a more recent version of vcpkg seems to have fixed
the issue, so that is what is proposed here.
The commit selected is current top of tree.
Original report: https://github.com/mcgoo/cargo-vcpkg/issues/9
> Update vcpkg rev to unblock Windows

- changelog.md
- src/sdl2/lib.rs
- src/sdl2/url.rs
> Added binding for `SDL_OpenURL`

- README.md
The example for vulcan in the README.md is outdated. This commit changes the code to work with the actual version 0.25.0 of vulcano.
> Updates vulcan example

- src/sdl2/render.rs
- src/sdl2/video.rs
`RenderFlush` in particular is quite important with egui_sdl2_gl when using SDL2 with `Canvas`.
> Bind new functions: SDL_GL_GetCurrentContext and SDL_RenderFlush

- src/sdl2/controller.rs
Fixes #1128.
Fixes #1154.
Changes the panics to `return None` and implements the following button types:
```
SDL_CONTROLLER_BUTTON_MISC1
SDL_CONTROLLER_BUTTON_PADDLE1
SDL_CONTROLLER_BUTTON_PADDLE2
SDL_CONTROLLER_BUTTON_PADDLE3
SDL_CONTROLLER_BUTTON_PADDLE4
SDL_CONTROLLER_BUTTON_TOUCHPAD
```
> Fix panic on unrecognized controller buttons and axes

- README.md
- sdl2-sys/build.rs
1. Added a couple of libraries required to use static-link feature on macOS and Android.
2. Added a small instruction on how to set rpath for macOS and Linux.
The second point is actually a bit interesting: right now you can the `bundled` feature on macOS and Linux works differently when you run binaries/tests/benches via cargo and when you run the binary directly. This happens because cargo sets a few env vars: https://doc.rust-lang.org/cargo/reference/environment-variables.html#dynamic-library-paths and causes a lot of confusion (either the binary does not run with error such as `dyld: Library not loaded: @rpath/libSDL2-2.0.dylib` or picks up the system (probably, outdated) copy of the library).
> Fixed static-link on macOS and Android and added instructions for distributing bundled library

- README.md
- changelog.md
- src/sdl2/raw_window_handle.rs
Added support for raw-window-handle on Android. Tested with wgpu 0.11 Vulkan and GLES backends on Android 10.
> Add Android raw window handle support

- changelog.md
- src/sdl2/event.rs
- src/sdl2/video.rs
Added `SDL_GetDisplayOrientation` bindings. Added `SDL_DISPLAYEVENT` bindings for tracking orientation changes. I am not 100% sure about `transmute` in `DisplayEvent::from_ll` and can re-do it like the `WindowEvent` does.
Unfortunately, this branch includes changes from https://github.com/Rust-SDL2/rust-sdl2/pull/1164 as well.
> Added display orientation support

- src/sdl2/timer.rs
- Closes #1166
- `TimerCallback` has type: `Box<dyn FnMut() -> u32 + 'a + Send>`
> Fix timer callback type

- Cargo.toml
- src/sdl2/raw_window_handle.rs
This is required for Rust-SDL2 to work with the latest version of WGPU.
This would usually be a breaking change, but thankfully `raw-window-handle` have used the [semver trick](https://github.com/dtolnay/semver-trick) to [do a compatibility release of 0.3](https://github.com/rust-windowing/raw-window-handle/pull/74). This means that any 0.4 `HasRawWindowHandle` also implements the 0.3 `HasRawWindowHandle` (hence why the WGPU example hasn't broken as a result of this change).
I did try to update the WGPU example too, but I don't know the API well enough to do so.
I have tested this on Windows and it seems to work - I don't have any way of testing other OSes, but the API changes seem fairly uniform, so hopefully it should all be fine? Will wait and see how the CI build goes :)
Summary of …
> Update raw-window-handle to 0.4

- src/sdl2/raw_window_handle.rs
Now that #1182 is merged the crate is up to date with the latest `raw-window-handle` release. This release contains the results of my [PR](https://github.com/rust-windowing/raw-window-handle/pull/68) from February which adds support for WinRT (UWP) to the crate. `raw-window-handle` now exposes a WinRt variant which contains an opaque c_void pointer to what is expected to be a CoreWindow*. SDL2 provides the same mechanism with the `SDL_SYSWM_WINRT` enum variant and the `winrt` field on `SDL_SysWMinfo`, which is what I modeled the WinRt variant in `raw-window-handle` after.
As a result, this PR includes the additions necessary to shim the CoreWindow pointer from SDL2 to `raw-window-handle`, allowing the use of this crate on UWP.
The changes simply adds the required match branch to output …
> Implement WinRT support in SDL2 raw-window-handle shim

- tests/events.rs
When I ran `cargo test` I got this failure:
```
test test_events ... ok
test test_event_sender_no_subsystem ... FAILED
failures:
---- test_event_sender_no_subsystem stdout ----
thread 'test_event_sender_no_subsystem' panicked at 'called `Result::unwrap()` on an `Err` value: "Cannot initialize `Sdl` more than once at a time."', tests/events.rs:106:28
stack backtrace:
0: rust_begin_unwind
at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
1: core::panicking::panic_fmt
at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
2: core::result::unwrap_failed
at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
3: core::result::Result<T,E>::unwrap
at …
```
> Fix failure on running events tests in parallel

- examples/audio-queue-squarewave.rs
- src/sdl2/audio.rs
Hi, thank you for developing the nice binding library. I enjoyed trying some SDL2 features with this library.
I noticed that `AudioQueue::queue` is not so idiomatic Rust API. It returns if it succeeded as `bool`. This PR replaces the return value with more idiomatic `Result` type. I believe `Result` is better because
- Rust compiler does not complain about missing error handling if it returns bool. Actually `audio-queue-squarewave` example missed the error handling.
- When an error occurs, user needs to get the error message via `sdl::get_error`. This is not idiomatic error handling and the error message may be overwritten by other errors.
I'm not sure that this change is appropriate because I'm new to both rust-sdl2 and SDL2. Please feel free to reject this PR if it's not appropriate.
> Return `Result` from `AudioQueue::queue` instead of `bool`

- README.md
Before this commit, there were separate instructions for build.rs in the section for the feature `bundled` on macos and linux but now there is a single merged build script that uses rust's conditional compilation features to merge the 2 codeblocks into 1 universal codeblock. None of the two codeblocks run if the operating system is windows or other.
> Update README.md to merge "Bundled" section Codeblocks

- README.md
Fixes a minor issue in the README where instructions to use rpath for linking against libSDL2 did not use attribute syntax.
> Update README.md to fix attribute syntax for rpath instructions

- examples/game-controller.rs
- sdl2-sys/sdl_bindings.rs
- src/sdl2/audio.rs
- src/sdl2/controller.rs
- src/sdl2/event.rs
- src/sdl2/joystick.rs
- src/sdl2/surface.rs
- src/sdl2/video.rs
Notes:
- Bindings were generated using `SDL2_INCLUDE_PATH=path/to/SDL-2.0.20/include cargo build --features use-bindgen`
- I'm still fairly new to Rust development, so apologies for any amateur mistakes. Any feedback is welcome
- New renderer features moved to https://github.com/Rust-SDL2/rust-sdl2/pull/1216
> Update bindings to SDL 2.0.20

- Cargo.toml
- changelog.md
- examples/raw-window-handle-with-wgpu/main.rs
As described in https://github.com/Rust-SDL2/rust-sdl2/issues/1224, updates wgpu to latest version and fixes the wgpu example program so that it runs and displays the triangle.
> Update wgpu to 0.12 and fix raw-window-handle-with-wgpu example program.

- examples/game-controller.rs
Fixes #1230.
An alternative fix for this would be to enable the video subsystem, but since this example doesn't use it, this seems a bit cleaner.
> Fix XInput support in the game-controller example (fixes #1230)

- README.md
- changelog.md
Closes #1244.
---
I stuck with the "recommended" wording because while linking on Windows flat out fails with an older version, linking on Linux works fine as long as you don't actually have a call to `sdl2::url::open_url()`.
> Update README and changelog with new min SDL2 version

- sdl2-sys/build.rs
Fixes [the following error](https://github.com/Rust-SDL2/rust-sdl2/runs/7975841404?check_suite_focus=true)
```
error: could not find native static library `SDL2`, perhaps an -L flag is missing?
error: could not compile `sdl2-sys` due to previous error
```
On Windows it currently outputs a `SDL2-static.lib` instead of `SDL2.lib`.
> Fix build error on Windows with `bundled` and `static-link` features

- changelog.md
- src/sdl2/surface.rs
This patch changes the Surface to receive the PixelMasks by refrence not
a moved value. This avoids continous reconstruction of a PixelMasks
struct when using the from_data_pixelmasks method to create a
surface many times.
> Surface: take PixelMasks by refrence not value

- changelog.md
- src/sdl2/keyboard/mod.rs
- src/sdl2/mouse/mod.rs
- src/sdl2/sdl.rs
Fixes #1247 and #1248. Ensures better initialization/drop guarantees for `SdlDrop` and `SubsystemDrop` by using global reference counts. This has a few caveats:
* `SdlDrop` can no longer be initialized from outside the `crate::sdl` module. Any external code depending on this (hopefully there was none because this is extremely unsafe) will break.
* Public but hidden functions returning `SdlDrop` and `SubsystemDrop` are no longer wrapped in `Rc<>`. Any external code depending on these functions will break. It would be possible to reverse this change, but with global reference counting, there is no longer any good reason to do so.
* The fixes caused at least one of the tests to break because tests are run in parallel by default, and more than one test initializes SDL. Now that this can only …
> Make SdlDrop and SubsystemDrop safer to use

- changelog.md
- src/sdl2/timer.rs
It is safe to call `TimerSubsystem::delay()` with an immutable reference to `&self` as long as the subsystem is initialized. It otherwise breaks the ability to create timers. Closes #1268
> Remove &mut self requirement in TimerSubsystem::delay()

- src/sdl2/pixels.rs
Fixes #1271. The bytes per pixel just needed to be changed from 2 to 1.
> Fixed Canvas::read_pixels segfault

- Cargo.toml
- examples/raw-window-handle-with-wgpu/main.rs
- examples/raw-window-handle-with-wgpu/shader.wgsl
- src/sdl2/raw_window_handle.rs
- src/sdl2/video.rs
- tests/raw_window_handle.rs
Resolves #1269 
I tested this on:
- Linux with X11: raw-window-handle test pass and the example shows the triangle.
- Windows with Win32: raw-window-handle test pass and the example shows the triangle.
- MacOS: The example works and shows the triangle. We need SDL to construct a `SDL_MetalView` though, which likely means one can only use Metal afterwards. The test fails to run with the same error as in #1151. The mentioned issue is caused by `cargo test` using multiple threads.
Other platforms are best effort guess work.
> Update raw-window-handle to 0.5.0

- sdl2-sys/build.rs
Fixes #1259
Without `SDL_MAIN_HANDLED` SDL will provide it own `main` function which cause a conflict with C/C++ program this crate linked to.
See https://github.com/libsdl-org/SDL/blob/main/include/SDL_main.h#L38 for a reference.
> Fix linking error when linked to C/C++ program

- src/sdl2/video.rs
`sdl2-sys` has been updated since its latest release and exposes `SDL_WINDOWS_ALWAYS_ON_TOP`.
The [documentation](https://wiki.libsdl.org/SDL2/SDL_WindowFlags) for `SDL_WindowFlags` says it's *X11 only*, but that's not the case anymore since it seems to be used in the [windows](https://github.com/libsdl-org/SDL/blob/07d0f51fa292895443f563f0cbde4cb3802d87fa/src/video/windows/SDL_windowswindow.c#L239) and [cocoa](https://github.com/libsdl-org/SDL/blob/07d0f51fa292895443f563f0cbde4cb3802d87fa/src/video/cocoa/SDL_cocoawindow.m#L1036) backends as well in the same tagged version of the headers currently used by sdl2-sys (I checked those arbitrarily so it may be supported by more plataforms).
Tested on Linux under X11 with version 2.26.5
> Exposing window always on top functionality

- changelog.md
- src/sdl2/audio.rs
- src/sdl2/render.rs
- src/sdl2/video.rs
[`size_hint` returns the _remaining_ size of the iterator,](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint) but these iterators have been returning the _total_ size.
> fix size_hint implementations in driver iterators

- changelog.md
- src/sdl2/sdl.rs
Fix #1323
This addresses the issue above, which seems to have been introduced by #1254, which added a flag to indicate which thread was initialized as the main thread. This flag was never cleared which meant that only one thread would ever be the main, if SDL was then quit and attempted to initialize on another thread (while still only having 1 context) it would fail.
If the intention of `IS_MAIN_THREAD` was to only allow `SDL_Init` to be invoked once per application, I can find another solution. But I believe there is nothing wrong with this, `SDL_Init` itself is reference counted, and the tests show an expectation to be able to do so.
> Fix "Cannot initialize Sdl from more than one thread" for tests / CI

- sdl2-sys/build.rs
Versions of SDL since https://github.com/libsdl-org/SDL/commit/5b65e0af01873e26673c11da43001e7075986290 fail to build if this isn't set.
Credit to @ciciplusplus for finding this issue while porting touchHLE to Android.
Btw, I've only tested the dynamically-linked bundled build. I think statically-linked builds might still be broken for other reasons, but they're unrelated to this commit.
> Fix Android bundled build: define ANDROID_NDK CMake variable

- changelog.md
- src/sdl2/audio.rs
- src/sdl2/render.rs
- src/sdl2/video.rs
After writing #1332, I figured I'd offer these for good measure.
> implement `FusedIterator`, `DoubleEndedIterator`, and `nth[_back]` for driver iterators

- src/sdl2/rect.rs
I noticed there are some useful functions missing that could improve the ergonomics of the library. One of them is `center_on` which doesn't return `self` (which doesn't allow chaining functions), thus I added `centered_on`, that reuses the same logic. I'm not sure about it, but I also `#[inline]`d the related functions.
> Add Rect::centered_on

- sdl2-sys/build.rs
While playing around with this library I notices an annoying problem.
When building the library with the `bundled` feature and having the [CMAKE_GENERATOR](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR.html) environment variable set to a so called multi-config generator like [Ninja Multi-Config](https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html) the build for sdl2 fails.
This patch fixes this annoyance by simply also settings the [CMAKE_CONFIGURATION_TYPES](https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIGURATION_TYPES.html) for these builds since the normal [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) variable is ignored when using multi-config generators.
With that we essentially create a …
> Fix cmake build failure when using multi-config generators

- src/sdl2/video.rs
This branch adds the support of shaped windows.
Usage example:
```rust
let mut builder =  sdl2::video::WindowBuilder::new(&video_subsystem, "title", width, height).set_shaped();
let mut shape_surface = sdl2::surface::Surface::from_data(
&mut shape_data,
width,
height,
width * 4,
sdl2::pixels::PixelFormatEnum::RGBA8888,
)
.map_err(|err| anyhow!("Cannot laod surface {}", err))?;
let ret = window.set_window_shape(&mut shape_surface);
```
> Add shape window

- src/sdl2/raw_window_handle.rs
Hi!
Quick PR for a small bug I hit with the android code for 'raw_display_handle'. `a_native_window` got moved onto `AndroidWindowHandle` with the newer version of `raw-window-handle` and was removed from `AndroidDisplayHandle`. I think a simple copy-paste error left the old code assigning to the now missing field and there's no regular android builds so it got missed.
Fix is trivial, remove the assignment. I also removed 'mut' declarations from other handles that weren't assigned to.
> Fix compile error when building for android in raw_display_handle implementation

- src/sdl2/video.rs
Makes it clonable and removes the "unsafe" from the `Window::from_ref` method.
Addresses #1367
> Improve the UX of the Window interface.

- sdl2-sys/Cargo.toml
The `profile()` function used in `build.rs` was added to the `cmake` crate starting with version 0.1.4. Because of this, building projects that depend on SDL2 with `-Zminimal-versions` fails. I bumped it to 0.1.47 because this allows it to build with VS 2022 using `-Zminimal-versions`.
> Bump minimum cmake dependency to 0.1.47

- src/sdl2/controller.rs
Just bind more methods in `struct GameController`.
> controller: Add vendor_id() and product_id()

- Cargo.toml
- examples/raw-window-handle-with-wgpu/main.rs
- src/sdl2/raw_window_handle.rs
- tests/raw_window_handle.rs
I implemented HasWindowHandle and HasDisplayHandle for Window, though its not send/sync due to it containing the underlying pointer to SDL_Window, preventing it from being used with wgpu without unsafe. Still, I updated the raw-window-handle/wgpu example to work with the most current version of both libraries.
Should fix https://github.com/Rust-SDL2/rust-sdl2/issues/1376
I ran cargo check on the code for other platforms, but I don't have access to anything but my linux machine right now. I feel especially iffy about iOS code, as the required field changed from UI_Window to UI_View.
I'm hoping to find a better solution to implement send/sync for Window than just wrapping it in Arc<Mutex<>>, partially because it smells bad, and partially because it looks like it'll take a long time.
> Upgrade to raw-window-handle 0.6

- src/sdl2/sdl.rs
EventPump is thread-safe in the sense that it ensures it's only created on the main SDL thread to enforce invariants required by SDL, but it's not thread-safe is the usual meaning of "can be safely accessed from multiple threads".
Fixes #835.
> fix documentation on EventPump

- sdl2-sys/build.rs
This should cut down almost 90 MB from initializing SDL git module every time this crate is download.
cc #1313
> do not init submodule if not enabling bundle feature

- src/sdl2/rect.rs
Currently, the rect shifted methods offsets itself by the shifted amount on one axis, and by the rect point on the other. The expected behavior is that the rect is shifted on one axis, while the other one stays the same.
This change sets the offset of the other axis to 0, as well as changing the tests to better cover these edge cases.
> Fix rect shifted logic

- sdl2-sys/build.rs
Re-enables static linking when `static-link` is enabled on its own, without any other packaging features, like `use-pkgconfig`. This fixes a regression introduced in https://github.com/Rust-SDL2/rust-sdl2/pull/1352.
> Fix static linking

- changelog.md
- sdl2-sys/examples/no_std.rs
- sdl2-sys/sdl_bindings.rs
- src/sdl2/log.rs
- src/sdl2/pixels.rs
- src/sdl2/rect.rs
- src/sdl2/render.rs
- src/sdl2/rwops.rs
- src/sdl2/ttf/font.rs
review note: read_pixels had some indentation changed, word diff looks better to see what changed there
fix some undefined behavior (not all changes are)
f374447d103898542afcc789e0f00d0667759ae2 removes an unnecessary call to an unsafe function and 2accf9909cc3342176084897d4819ef5b08d43b6 fixes a memory leak
> Fix some undefined behavior

- changelog.md
- src/sdl2/sdl.rs
The field `_anticonstructor` is always initialized with the same value (null pointer), so may be zero sized as well.
SdlDrop will remain !Send and !Sync with a pointer inside PhantomData.
> make SdlDrop zero sized and use more conventional field name

- README.md
Following the current instructions for Windows (MSVC) will result in a compile error with the latest Rust 1.83 version:
`LINK : fatal error LNK1181: cannot open input file SDL2.lib`
The issue does not occur with older versions of Rust (1.80).
The solution is to copy the `SDL2.lib` file to the project directory along with the `SDL2.dll` file.
This PR is intended to update the instructions for Windows (MSVC) accordingly.
> Update Windows (MSVC) instructions

- src/sdl2/video.rs
Found this bug when looking at recent issues, was a very quick fix.
Is this worthy for the changelog? I don't think library users would be interested because it requires no change on their part.
> Fix copy-paste mistake in WindowBuilder::build

- src/sdl2/render.rs
no changelog entry needed - wasn't added in both because I didn't realize the dup.
relates: https://github.com/Rust-SDL2/rust-sdl2/pull/1444
> add scale mode - unsafe textures

- changelog.md
- src/sdl2/video.rs
- gamma_ramp_arrays is similar to gamma_ramp, but returns the gamma ramps as an array of 3 arrays, this way no heap allocations are made and users get a compile time guarantee that each ramp contains 256 values
- calculate_gamma_ramp wraps SDL_CalculateGammaRamp, which calculates the gamma ramp for a gives gamma value, see https://wiki.libsdl.org/SDL2/SDL_CalculateGammaRamp
> add gamma_ramp_arrays and calculate_gamma_ramp

- changelog.md
- src/sdl2/ttf/context.rs
- src/sdl2/ttf/font.rs
- src/sdl2/ttf/mod.rs
Detailed description of the changes are in the commit messages
> Prevent users from creating `Sdl2TtfContext` out of nothing and use SDL's reference counting init/quit

- changelog.md
- src/sdl2/sensor.rs
First change updates get_data for Gyroscope to return the proper SensorData::Gyro instead of Accel. I think this matches the intended behavior, if not I can undo this. This might change might need to be added to the change log. Let me know if that is the case. 
Second change updates SensorTypes to account for new SDL bindings that were added for joycons. This change should address issue #1428.
> Update sensor types and Return correct SensorData Enum

- sdl2-sys/build.rs
On windows the ANDROID_NDK_HOME path can use backslashes. This causes issues in cmake. Replaces \ with / on windows compilation hosts.
> Replace slashes in NDK path when building for android on windows

- changelog.md
- src/sdl2/event.rs
- src/sdl2/hint.rs
- src/sdl2/lib.rs
- src/sdl2/locale.rs
Includes:
- https://wiki.libsdl.org/SDL2/SDL_GetPreferredLocales
- https://wiki.libsdl.org/SDL2/SDL_Locale
- https://wiki.libsdl.org/SDL2/SDL_HINT_PREFERRED_LOCALES
- `SDL_LOCALECHANGED` event.
> Added system locale support

- changelog.md
- src/sdl2/audio.rs
- src/sdl2/filesystem.rs
- src/sdl2/mixer/mod.rs
- src/sdl2/rect.rs
- src/sdl2/timer.rs
Breaking changes:
- `mixer::Chunk` fields were made private because the struct relied on these pointer being valid, but users could set them to any value
- Timer callback must live for `'static` because the callback can be called after the scope ends (by using `std::mem::forget`).
timer ub reproduction (ran from a `#[test]`):
```rust
let sdl_context = crate::sdl::init().unwrap();
let timer_subsystem = sdl_context.timer().unwrap();
let mut v = Box::new(123);
std::mem::forget(timer_subsystem.add_timer(
20,
Box::new(|| {
dbg!(std::mem::take(&mut v));
0
}),
));
drop(v);
// v is used after dropping (from the timer callback)
std::thread::sleep(Duration::from_millis(30));
```
> Fix ub and shrink unsafe blocks

- src/sdl2/gfx/primitives.rs
> replace unsound use of transmute with u32::from_be_bytes

- Cargo.toml
- changelog.md
- examples/render-geometry.rs
- src/sdl2/pixels.rs
- src/sdl2/render.rs
~Draft while I check if this covers my use case.~ It does.
> Render geometry binding

- src/sdl2/locale.rs
The type of the pointer from libc may change depending on the target architecture. Pass the libc type instead.
> fix: Change type signature of try_get_string in locale.rs

- src/sdl2/video.rs
Provided documentation for most of the `sdl2::video` functions.
Mostly did that to resolve some uncertanties in functions purposes (`grab`/`keyboard_grab`/`mouse_grab`, `minimize`).
Apparently, `grab` only grabs the mouse.
SDL documentation:
when input is grabbed, the mouse is confined to the window. This function will also grab the keyboard if SDL_HINT_GRAB_KEYBOARD is set. To grab the keyboard without also grabbing the mouse, use SDL_SetWindowKeyboardGrab().
Since we can't set SDL_HINT_GRAB_KEYBOARD and by default it is set to 0, `grab` operates exactly as `mouse_grab` (which makes it kinda pointless).
`minimize` does not set the minimal size of window's client area (`minimum_size`), it minimizes the window to its iconic representation (without docs it would be confusing).
Looked at …
> Documentation for `sdl2::video`

- changelog.md
- src/sdl2/rect.rs
Answers #1492
The goal is to ensure the origin location is understood and made available to users, as this point is used as a basis for transformations and positioning. Would work in stride with [`Rect::center`](https://github.com/Rust-SDL2/rust-sdl2/blob/master/src/sdl2/rect.rs#L304C18-L304C20).
> Add `Rect::origin` and update `Rect::new` to specify the origin location of rectangles.

- src/sdl2/controller.rs
- src/sdl2/joystick.rs
Exposes `SDL_JoystickSetPlayerIndex`, `SDL_JoystickGetPlayerIndex`, `SDL_GameControllerSetPlayerIndex`, `SDL_GameControllerGetPlayerIndex`, and `SDL_JoystickGetDevicePlayerIndex`.
Additionally exposes `SDL_JoystickFromPlayerIndex`, and `SDL_GameControllerFromPlayerIndex` using instance IDs instead of joysticks/controllers to match Controller events (unless I'm missing something, we can't get a Joystick's device index from its object, so that cannot match the corresponding event format).
> Add player index functions for game controller and joystick
