Rust-SDL2/rust-sdl2

src/sdl2/keycode.rs
src/sdl2/scancode.rs

Fixes warnings with latest Rust nightly.
https://github.com/rust-lang/rust/commit/74d11d26f4042ce04c56edfd6caafa003383147d

Change mod to self

---

src/sdl2/audio.rs
src/sdl2/keycode.rs
src/sdl2/scancode.rs
src/sdl2/surface.rs

Fixes errors with latest Rust nightly.

Primitive imports

---

examples/demo.rs

Simplify demo

---

examples/demo.rs

I hope this change is welcome, but it just sprung in my face as I checked it out! So I thought why not change it myself :smile:

Reformatted demo code to be more readable

---

examples/demo.rs
examples/renderer-texture.rs
src/sdl2/event.rs

A new PR here to replace https://github.com/AngryLawyer/rust-sdl2/pull/301 for a clean commit history.

Reform for Event enum

---

src/sdl2/event.rs

Use `window_id` on Event struct instead of `window`. Fixes #101 
This change has the additional advantage of simplifying the creation of Event objects. They're now simple structures that can be easily created for unit tests.
@AngryLawyer @mikhels

Use window_id on Event struct instead of window

---

sdl2-sys/src/audio.rs
sdl2-sys/src/controller.rs
sdl2-sys/src/event.rs
sdl2-sys/src/haptic.rs
sdl2-sys/src/joystick.rs

This fixes a bunch of compile warnings in sdl2-sys.

Change Xus literals to Xusize literals in sdl2-sys

---

Cargo.toml
examples/audio-whitenoise.rs
examples/game_controller.rs
examples/joystick.rs
examples/renderer-texture.rs
examples/renderer-yuv.rs
sdl2-sys/Cargo.toml
sdl2-sys/src/audio.rs
sdl2-sys/src/controller.rs
sdl2-sys/src/event.rs
sdl2-sys/src/haptic.rs
sdl2-sys/src/joystick.rs
src/sdl2/audio.rs
src/sdl2/clipboard.rs
src/sdl2/controller.rs
src/sdl2/event.rs
src/sdl2/filesystem.rs
src/sdl2/joystick.rs
src/sdl2/keyboard.rs
src/sdl2/keycode.rs
src/sdl2/lib.rs
src/sdl2/messagebox.rs
src/sdl2/render.rs
src/sdl2/rwops.rs
src/sdl2/scancode.rs
src/sdl2/sdl.rs
src/sdl2/timer.rs
src/sdl2/version.rs
src/sdl2/video.rs
tests/lib.rs

Basically #340 plus fixing warnings.

Fixes both compilation, and warnings

---

sdl2-sys/src/audio.rs
sdl2-sys/src/controller.rs
sdl2-sys/src/event.rs
sdl2-sys/src/haptic.rs
sdl2-sys/src/joystick.rs

Take away the unnecessary usize suffixes

---

README.md

Information on how to install SDL2 development libraries on Windows.

Added windows installation guide.

---

Cargo.toml
sdl2-sys/Cargo.toml
sdl2-sys/build.rs
src/sdl2/lib.rs

Change to underscores from hyphens

---

Cargo.toml
sdl2-sys/Cargo.toml
sdl2-sys/build.rs
src/sdl2/lib.rs

Reverts AngryLawyer/rust-sdl2#365

Revert "Change to underscores from hyphens"

---

Cargo.toml
sdl2-sys/Cargo.toml
sdl2-sys/build.rs
src/sdl2/lib.rs

Closes https://github.com/AngryLawyer/rust-sdl2/issues/364

Changed to underscore in crate name

---

examples/game_controller.rs
examples/joystick.rs
src/sdl2/audio.rs
src/sdl2/event.rs

Upgrade to latest rust

---

sdl2-sys/src/event.rs
sdl2-sys/src/haptic.rs
sdl2-sys/src/rwops.rs
src/sdl2/event.rs

Closes https://github.com/AngryLawyer/rust-sdl2/issues/302

_type --> type_

---

examples/demo.rs
examples/renderer-texture.rs
examples/renderer-yuv.rs
src/sdl2/render.rs
src/sdl2/surface.rs
src/sdl2/video.rs

This includes the (rebased+squashed) changes that were mentioned in PR #390.
Fixes #322
Closes #351

Remove Texture lifetime, Window thread safety fixes

---

.travis.yml

We also make sure that the docs are only updated when building beta

Test both nightly and beta on travis

---

examples/audio-squarewave.rs
examples/audio-whitenoise.rs
examples/demo.rs
examples/game_controller.rs
examples/joystick.rs
examples/renderer-texture.rs
examples/renderer-yuv.rs
src/sdl2/audio.rs
src/sdl2/event.rs
src/sdl2/lib.rs
src/sdl2/render.rs
src/sdl2/sdl.rs
src/sdl2/timer.rs
src/sdl2/video.rs

Add builders for Window, Renderer and init

---

src/sdl2/video.rs

More breaking changes headed your way!
Yet another nit of mine is how GL attributes are handled. `gl_set_attribute()` and `gl_get_attribute()` were not type-safe, in particular with getting/setting profiles and context flags. Boolean-like attributes would also have to be set to 1 or 0 for true or false, although we could clearly use actual booleans instead.
So, with the power of macros (it's not that bad, promise), getter and setter pairs are generated for each attribute!
This is what the documentation looks like: https://nukep.github.io/rust-sdl2/sdl2/video/gl_attr/index.html
```rust
use sdl2::video::{GLProfile, gl_attr};
// Don't use deprecated OpenGL functions
gl_attr::set_context_profile(GLProfile::Core);
// Set the context into debug mode
gl_attr::set_context_flags().debug().set(); …
```

Overhaul GL attributes to use type-safe getters/setters

---

README.md

I do not know if you want to add it, but here is the PR, it still is your choice.

add sdl2_net to README.md

---

README.md

Adding a section to the readme for those who use macports as their OSX package manager. Also added info about LIBRARY_PATH so that users are less likely to have to hunt through the issues.

Adding macports usage.

---

README.md

Well, I struggled a bit: http://stackoverflow.com/questions/31278956/sdl2-sys-wont-compile

Added Fedora example and gcc.

---

README.md

New endpoint has updates via Travis \o/

Point to new documentation

---

examples/window-properties.rs
src/sdl2/audio.rs
src/sdl2/clipboard.rs
src/sdl2/controller.rs
src/sdl2/cpuinfo.rs
src/sdl2/filesystem.rs
src/sdl2/joystick.rs
src/sdl2/keyboard/mod.rs
src/sdl2/mouse.rs
src/sdl2/pixels.rs
src/sdl2/render.rs
src/sdl2/surface.rs
src/sdl2/timer.rs
src/sdl2/touch.rs
src/sdl2/version.rs
src/sdl2/video.rs
tests/lib.rs

Remove all get_ prefixes from getter methods

---

src/sdl2/event.rs
src/sdl2/joystick.rs
src/sdl2/rect.rs
src/sdl2/render.rs
src/sdl2/sdl.rs
src/sdl2/surface.rs
src/sdl2/util.rs
src/sdl2/video.rs

Wrap error messages in an ErrorMessage type

---

examples/audio-wav.rs

Addresses #458.
Outstanding issues:
cc @nukep I figured out the `AudioCVT` thing, thanks for the hint.

Add an example of playing a WAV file.

---

src/sdl2/render.rs

`SDL_UpdateYUVTexture` does not perform any bounds checking on the destination
rectangle, so it needs to be done on the Rust side in order to have a safe
interface.

Fix segfault if destination rectangle in update_yuv is outside texture bounds

---

README.md

Fix the OpenGL initialization code in the README

---

README.md

As I said in #479, this caused me confusion and I could see it causing confusion for others, so I think this will help others in the future :smile:

Updated README to help the Windows multirust users

---

examples/audio-squarewave.rs
examples/audio-wav.rs
examples/audio-whitenoise.rs
src/sdl2/audio.rs

Not necessary to move the value.

Take desired audio spec as reference

---

Cargo.toml
src/sdl2/event.rs
src/sdl2/lib.rs
tests/events.rs

Hi there,
I'm trying to use the SDL event loop as the main event loop for an UI application, so I've added a function to register user events, and extended `Event::User` to include the raw data pointers.

Improve user events

---

examples/demo.rs
src/sdl2/video.rs

* Solves #457
* Also added `FullscreenType::from_window_flags(u32) -> FullscreenType`

Added a way to retrieve window fullscreen state

---

src/sdl2/rect.rs

* Also added an very simple example in the docs
* Closes #505

doc: Added test to center() in rect.rs

---

src/sdl2/render.rs

Fixed renderer.info() crash on some machines

---

sdl2-sys/src/controller.rs
src/sdl2/controller.rs

It can be tested with the file provided by [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB).

Add SDL_GameControllerAddMappingsFromRW bindings

---

sdl2-sys/src/pixels.rs
src/sdl2/pixels.rs

Fixes #500.
Please point out any style errors I've made and I'll work on fixing those.

Add public interface for creating Palettes

---

src/sdl2/rect.rs

Adds some new methods and traits for Rect and Point, to make them more convenient to work with.
Rect gains topleft(), topright(), etc. methods to go along with the existing center() method, as well as a size() method that gets the width and height simultaneously.
Point gains a scale() method to go along with the existing offset() method, as well as support for basic arithmetic operators for doing simple vector calculations (e.g. (point1 + point2) / 2).  These new operators clamp output values the same way that e.g. offset() does.

Add some convenience methods/operators for Rect and Point

---

src/sdl2/filesystem.rs

Trivially addresses issue #533

Make sdl2::filesystem::PrefPathError derive Debug

---

src/sdl2/audio.rs

Expose obtained AudioSpec on both AudioDevice and AudioQueue 

---

src/sdl2/render.rs

Improve documentation for RendererBuilder.

---

src/sdl2/video.rs

Fix type of format field in video::DisplayMode

---

src/sdl2/mixer/mod.rs

`Music` continues to load from its RWops while it's playing, so it should not be allowed to outlive the RWops.

Prevent Music from outliving the RWops it's created from

---

.gitignore

add intellij projects to gitignore

---

src/sdl2/rect.rs

add Deref to Rect for underlying C type

---

src/sdl2/rect.rs

add AsRef and AsMUt for Rect on ll::SDL_Rect

---

src/sdl2/rect.rs

Forgot to include DerefMut in the previous PR #596.

Add Deref and DerefMut for Rect on ll::SDL_Rect

---

src/sdl2/rect.rs

add Into and From for Rect primitive types

---

src/sdl2/messagebox.rs

add Into and From between primitive for MessageBoxColorScheme

---

README.md

Add Windows build script instructions as requested here: https://github.com/AngryLawyer/rust-sdl2/issues/609

Add Windows build script instructions

---

README.md

I forgot a step when I wrote this up last night, here's that step.

Add .gitignore changes to Windows instructions

---

.travis.yml

This should fix our travis builds.  Documentation for sourceforge downloads found at: https://sourceforge.net/p/forge/documentation/Downloading%20files%20via%20the%20command%20line/#download-ninja

Fix up travis

---

README.md

The current OpenGL section isn't helpful when setting up an OpenGL view.

Updated readme with working OpenGL setup

---

src/sdl2/mixer/mod.rs

Uppercase static variables

---

src/sdl2/mixer/mod.rs

Add chunksize parameter documentation

---

src/sdl2/render.rs

The following code will now work:
```
self.canvas.with_texture_canvas(
&mut self.buffer,
|canvas| {
{
let texture = cache.get(tile);
if texture.is_some() {
// this requires the buffer to be the render target
buffer_render_tile_(canvas, texture.unwrap(), y, x);
return;
}
}
// cache the new render and then copy it
let mut texture = gen(creator);
// this sets the render target
cache_render_tile(canvas, &mut texture, textures, tile, y, x);
// this requires the buffer to be the render target
buffer_render_tile_(canvas, &texture, y, x);
cache.insert((*tile).clone(), texture);
}).unwrap();
```

Make with_texture_canvas restore target.

---

README.md

Add missing unwrap

---

src/sdl2/audio.rs

Current example in `sdl2::audio` produce a warning.
Reference: 
* https://github.com/rust-lang/rust/issues/41620
* https://github.com/Rust-SDL2/rust-sdl2/pull/705

Updated sdl2::audio documentation

---

README.md

Hi there, just saw this little typo ;)

Fix path escaping

---

src/sdl2/video.rs

Resolves #755.
Sorry, forgot this was a thing for a while!

Made gl_set_swap_interval() return Result, not bool

---

src/sdl2/pixels.rs

Added 32-bit array pixelformats

---

src/sdl2/timer.rs

This is mostly to silence some dead-code warnings I was receiving on Mac OS. Grouping these tests allows a single `#[cfg(not(target_os = "macos"))]` to skip compilation of the entire suite. As a bonus, if the test failure is resolved, it can be re-enabled as with a one-line change.

Group timer tests

---

src/sdl2/video.rs

Return data from Window::gamma_ramp

---

src/sdl2/mixer/mod.rs

Wanted to add a comment to this to indicate that you can pass -1 to play forever.

Add infinite looping comment for Music.play

---

src/sdl2/video.rs

Is this the right way to document things?
Would you like more documentation like this?
I think it would be helpful ;)

Add documentation to set_icon

---

sdl2-sys/build.rs

Fix name of bundled SDL2.dll for windows targets

---

src/sdl2/audio.rs

It took me a while to figure out how to update the callback data, maybe
this will help someone.

Try to guide AudioDevice users towards the lock method

---

Cargo.toml
changelog.md
src/sdl2/pixels.rs

Remove dependency on the rand crate

---

src/sdl2/surface.rs

Implements SDL_ConvertSurfaceFormat wrapper

---

src/sdl2/controller.rs
src/sdl2/joystick.rs

Convert joystick instance IDs to u32s

---

src/sdl2/image/mod.rs

Resolves Rust-SDL2/rust-sdl2#983.

Fix lifetimes on ImageRWops

---

src/sdl2/rwops.rs

Fix building on windows

---

src/sdl2/video.rs

Implement From<i32> trait for WindowPos

---

src/sdl2/raw_window_handle.rs

Also added support in metal-raw-window, worked for me on device.
https://github.com/norse-rs/raw-window-metal/pull/1

Add support for generating raw window handle on iOS

---

sdl2-sys/build.rs
sdl2-sys/patches/SDL2-2.0.12-SDL_DISABLE_WINDOWS_IME.patch

https://github.com/Rust-SDL2/rust-sdl2/issues/1041

SDL_DISABLE_WINDOWS_IME

---

src/sdl2/event.rs
src/sdl2/render.rs

- 🎨 Avoid to call `description`
- 🔥 Remove unused code
- 🎨 Remove unnecessary braces

Resolve Warnings

---

src/sdl2/audio.rs

This allows opening audio capture devices.

Add num_audio_capture_devices and audio_capture_device_name

---

README.md

Reorder setup options

---

src/sdl2/rect.rs

implement sum trait for point

---

sdl2-sys/build.rs

Fedora uses "lib64" for the CMake output directory. The current search
path is limited to "lib". This fix searches in "lib" and "lib64 for
applicable libraries in a bundled build.

Fix bundled build on Fedora

---

README.md

This PR updates the instructions for macOS users to reflect changes to Homebrew.
Signed-off-by: Ismayil Mirzali <ismayilmirzeli@gmail.com>

Improve instructions for macOS

---

examples/game-controller.rs
src/sdl2/event.rs

Fulfills #1142 by mapping the SDL_ControllerTouchpadEvent events

Implement controller touchpad events

---

.gitmodules

Fix build for macOS (fix for PR 1227)

---

src/sdl2/raw_window_handle.rs

add support for emscripten to raw-window-handle

---

changelog.md
sdl2-sys/build.rs

Fix build error in manylinux docker container

---

Cargo.toml
examples/raw-window-handle-with-wgpu/main.rs

Some small API changes but nothing major.

Upgraded raw-window-handle-with-wgpu to use v0.15

---

README.md

Just had to learn this the hard way... so a heads up notice might help others

Add note  to not drop the window too early

---

src/sdl2/rect.rs

- Add Rect::*_shifted functions (left, right, up and down)
- Add examples
- `#[inline]`d all related functions

Add Rect::*_shifted functions

---

sdl2-sys/sdl_bindings.rs
src/sdl2/clipboard.rs
src/sdl2/video.rs

Exposes primary selection to rust api

Add primary selection API

---

src/sdl2/messagebox.rs

Fix use after free in show_message_box

---

README.md

Fixes #1340. This only works as of sdl2 0.36 and vulkano 0.34.

Fix UB in the vulkano example

---

src/sdl2/video.rs

Added a SDL_SetWindowResizable for sdl2::video::Window

Added a SDL_SetWindowResizable for sdl2::video::Window

---

src/sdl2/pixels.rs

fix function docs of Palette::new
see https://wiki.libsdl.org/SDL2/SDL_AllocPalette

fix function docs of Palette::new

---

changelog.md
sdl2-sys/build.rs
src/sdl2/audio.rs
src/sdl2/common.rs
src/sdl2/controller.rs
src/sdl2/event.rs
src/sdl2/filesystem.rs
src/sdl2/gfx/framerate.rs
src/sdl2/gfx/primitives.rs
src/sdl2/hint.rs
src/sdl2/joystick.rs
src/sdl2/keyboard/keycode.rs
src/sdl2/keyboard/mod.rs
src/sdl2/lib.rs
src/sdl2/log.rs
src/sdl2/macros.rs
src/sdl2/messagebox.rs
src/sdl2/mixer/mod.rs
src/sdl2/mouse/mod.rs
src/sdl2/mouse/relative.rs
src/sdl2/pixels.rs
src/sdl2/rect.rs
src/sdl2/render.rs
src/sdl2/sdl.rs
src/sdl2/surface.rs
src/sdl2/timer.rs
src/sdl2/ttf/context.rs
src/sdl2/ttf/font.rs
src/sdl2/url.rs
src/sdl2/video.rs

fixed a lot of the clippy errors/warnings on the project
some changes (regarding code readability) are opinionated, like 1c659cbe09f0dee00916dc845d0eb8af09b00288

Various code fixes including clippy suggestions

---

examples/raw-window-handle-with-wgpu/main.rs

Make wgpu example compile and run again

---

src/sdl2/video.rs

Does this need a changelog entry?

remove unnecessary clone
